import { StyleSheet } from 'react-native';
import { SPACING, TYPOGRAPHY, CARD, CARD_SHADOW } from '@/constants/designSystem';

const getDynamicStyles = (colors: any) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.background,
    },
    header: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingHorizontal: 16,
      paddingVertical: 12,
      backgroundColor: colors.surface,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: colors.border,
    },
    headerLeft: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: SPACING.md,
    },
    headerTitle: {
      fontSize: 18,
      fontWeight: '700',
      color: '#1B4D6E',
      position: 'absolute',
      left: 0,
      right: 0,
      textAlign: 'center',
    },
    headerMonthLabel: {
      fontSize: 13,
      fontWeight: '500',
      color: colors.textSecondary,
    },
    exportButton: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      paddingHorizontal: SPACING.md,
      paddingVertical: SPACING.sm,
      backgroundColor: colors.inputBackground,
      borderRadius: 8,
    },
    exportButtonText: {
      fontSize: 13,
      fontWeight: '600',
      color: colors.primary,
    },
    iconButton: {
      width: 36,
      height: 36,
      backgroundColor: colors.inputBackground,
      borderRadius: 18,
      alignItems: 'center',
      justifyContent: 'center',
    },
    filterContainer: {
      paddingHorizontal: SPACING.lg,
      paddingTop: SPACING.md,
      paddingBottom: SPACING.sm,
      backgroundColor: colors.surface,
    },
    summaryContainer: {
      flexDirection: 'row',
      paddingHorizontal: SPACING.lg,
      paddingVertical: SPACING.md,
      gap: SPACING.sm,
    },
    summaryCard: {
      flex: 1,
      backgroundColor: colors.cardBackground,
      borderRadius: CARD.borderRadius,
      padding: SPACING.sm,
      alignItems: 'center',
      gap: 2,
      ...CARD_SHADOW,
      borderWidth: CARD.borderWidth,
      borderColor: colors.border,
    },
    summaryIconRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
      marginBottom: 2,
    },
    summaryLabel: {
      fontSize: 9,
      color: colors.textSecondary,
      fontWeight: '700',
      textTransform: 'uppercase',
      letterSpacing: 0.5,
    },
    summaryAmount: {
      fontSize: 15,
      fontWeight: '700',
    },
    incomeAmount: {
      color: colors.success,
    },
    expenseAmount: {
      color: colors.error,
    },
    buttonRow: {
      flexDirection: 'row',
      paddingHorizontal: SPACING.lg,
      paddingBottom: SPACING.lg,
      gap: SPACING.md,
    },
    actionButton: {
      flex: 1,
      borderRadius: 8,
      overflow: 'hidden' as const,
    },
    incomeButton: {},
    expenseButton: {},
    actionButtonGradient: {
      flexDirection: 'row' as const,
      alignItems: 'center' as const,
      justifyContent: 'center' as const,
      gap: SPACING.sm,
      paddingVertical: 12,
      borderRadius: 8,
    },
    actionButtonText: {
      color: '#fff',
      fontSize: 13,
      fontWeight: '600',
    },
    sectionHeading: {
      fontSize: 12,
      fontWeight: '700',
      color: colors.textSecondary,
      paddingHorizontal: SPACING.lg,
      paddingBottom: SPACING.sm,
      textTransform: 'uppercase',
      letterSpacing: 1,
    },
    list: {
      padding: SPACING.lg,
      paddingTop: 0,
    },
    financeCard: {
      backgroundColor: colors.cardBackground,
      borderRadius: CARD.borderRadius,
      padding: SPACING.md,
      marginBottom: SPACING.sm,
      ...CARD_SHADOW,
      borderWidth: CARD.borderWidth,
      borderColor: colors.border,
    },
    financeHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: SPACING.md,
    },
    iconContainer: {
      width: 36,
      height: 36,
      borderRadius: 18,
      backgroundColor: colors.inputBackground,
      justifyContent: 'center',
      alignItems: 'center',
    },
    financeInfo: {
      flex: 1,
    },
    descriptionRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: SPACING.sm,
      marginBottom: 2,
    },
    financeDescription: {
      fontSize: 14,
      fontWeight: '600',
      color: colors.text,
      flex: 1,
    },
    jobBadge: {
      width: 16,
      height: 16,
      borderRadius: 8,
      backgroundColor: colors.success,
      alignItems: 'center',
      justifyContent: 'center',
    },
    recurringBadge: {
      width: 16,
      height: 16,
      borderRadius: 8,
      backgroundColor: colors.primary,
      alignItems: 'center',
      justifyContent: 'center',
    },
    financeMeta: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: SPACING.sm,
    },
    financeDate: {
      fontSize: 11,
      color: colors.textSecondary,
    },
    categoryBadge: {
      paddingHorizontal: SPACING.sm,
      paddingVertical: 2,
      borderRadius: 4,
      backgroundColor: colors.border,
    },
    categoryText: {
      fontSize: 10,
      color: colors.textSecondary,
      fontWeight: '600',
    },
    amountAndActions: {
      alignItems: 'flex-end',
      gap: SPACING.sm,
    },
    financeAmount: {
      fontSize: 15,
      fontWeight: '700',
    },
    deleteButton: {
      padding: SPACING.xs + 2,
      borderRadius: 6,
      backgroundColor: colors.inputBackground,
    },
    emptyContainer: {
      alignItems: 'center',
      justifyContent: 'center',
      paddingTop: SPACING.xxl * 2,
    },
    emptyText: {
      fontSize: 16,
      fontWeight: '600',
      color: colors.textSecondary,
      marginBottom: SPACING.sm,
    },
    emptySubtext: {
      fontSize: 13,
      color: colors.textSecondary,
      textAlign: 'center',
    },
    segmentedControl: {
      flexDirection: 'row',
      backgroundColor: colors.inputBackground,
      borderRadius: 8,
      padding: 3,
      marginHorizontal: SPACING.lg,
      marginBottom: SPACING.md,
    },
    segmentButton: {
      flex: 1,
      paddingVertical: SPACING.sm,
      paddingHorizontal: SPACING.md,
      borderRadius: 6,
      alignItems: 'center',
    },
    segmentButtonActive: {
      backgroundColor: colors.primary,
    },
    segmentButtonText: {
      fontSize: 13,
      fontWeight: '600',
      color: colors.textSecondary,
    },
    segmentButtonTextActive: {
      color: '#fff',
    },
    reportCard: {
      backgroundColor: colors.cardBackground,
      borderRadius: CARD.borderRadius,
      padding: SPACING.md,
      marginBottom: SPACING.sm,
      ...CARD_SHADOW,
      borderWidth: CARD.borderWidth,
      borderColor: colors.border,
    },
    reportHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: SPACING.md,
    },
    reportPeriod: {
      fontSize: 14,
      fontWeight: '700',
      color: colors.text,
    },
    reportRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      gap: SPACING.md,
    },
    reportItem: {
      flex: 1,
      alignItems: 'center',
    },
    reportLabel: {
      fontSize: 11,
      color: colors.textSecondary,
      marginBottom: SPACING.xs,
      fontWeight: '600',
    },
    reportAmount: {
      fontSize: 14,
      fontWeight: '700',
    },
    categoryBreakdown: {
      marginTop: SPACING.lg,
      paddingTop: SPACING.lg,
      borderTopWidth: StyleSheet.hairlineWidth,
      borderTopColor: colors.border,
    },
    categorySection: {
      marginBottom: SPACING.lg,
    },
    categorySectionTitle: {
      fontSize: 13,
      fontWeight: '700',
      color: colors.text,
      marginBottom: SPACING.sm,
    },
    categoryRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingVertical: SPACING.xs + 2,
      paddingHorizontal: SPACING.sm,
      backgroundColor: colors.inputBackground,
      borderRadius: 6,
      marginBottom: SPACING.xs + 2,
    },
    categoryName: {
      fontSize: 13,
      color: colors.text,
      flex: 1,
    },
    categoryAmount: {
      fontSize: 13,
      fontWeight: '600',
    },
  });

export default getDynamicStyles;
