import { StyleSheet } from 'react-native';
import { SPACING, TYPOGRAPHY, CARD, CARD_SHADOW, FAB, HEADER, COLORS } from '@/constants/designSystem';

export const getDynamicStyles = (colors: any) =>
  StyleSheet.create({
    root: { flex: 1, backgroundColor: colors.background },
    lockedContainer: { flex: 1, alignItems: 'center', justifyContent: 'center', padding: 32, gap: 12, backgroundColor: colors.background },
    lockedTitle: { fontSize: 20, fontWeight: '700', color: colors.text },
    lockedSub: { fontSize: 14, textAlign: 'center', lineHeight: 20, color: colors.textSecondary },

    header: { paddingHorizontal: SPACING.lg, paddingVertical: SPACING.md, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
    headerContent: { flexDirection: 'row', alignItems: 'center', gap: 10 },
    headerTitle: { fontSize: 20, fontWeight: '700', color: '#fff' },
    headerSub: { fontSize: 12, color: 'rgba(255,255,255,0.75)', marginTop: 1 },
    headerBadge: { backgroundColor: 'rgba(255,255,255,0.2)', paddingHorizontal: 10, paddingVertical: 4, borderRadius: 12 },
    headerBadgeText: { fontSize: 12, fontWeight: '600', color: '#fff' },

    tabBar: { flexDirection: 'row', borderBottomWidth: 1, borderBottomColor: colors.border },
    tabItem: { flex: 1, alignItems: 'center', paddingVertical: 12, borderBottomWidth: 2, borderBottomColor: 'transparent' },
    tabItemActive: {},
    tabText: { fontSize: 13, fontWeight: '600' },

    body: { flex: 1 },
    bodyContent: { padding: SPACING.md },

    sectionLabel: { fontSize: 11, fontWeight: '700', letterSpacing: 0.8, marginBottom: 10, marginTop: 4, color: colors.textSecondary },

    orgDefaultsBtn: { flexDirection: 'row', alignItems: 'center', gap: 12, padding: 14, borderRadius: 12, borderWidth: 1, marginBottom: 12, borderColor: colors.border, backgroundColor: colors.cardBackground, ...CARD_SHADOW },
    orgDefaultsBtnTitle: { fontSize: 14, fontWeight: '600', color: colors.text },
    orgDefaultsBtnSub: { fontSize: 12, marginTop: 1, color: colors.textSecondary },

    card: { borderRadius: 14, marginBottom: 10, borderWidth: 1, overflow: 'hidden', borderColor: colors.border, backgroundColor: colors.cardBackground, ...CARD_SHADOW },
    cardRow: { flexDirection: 'row', alignItems: 'center', padding: 14, gap: 12 },
    avatar: { width: 42, height: 42, borderRadius: 21, alignItems: 'center', justifyContent: 'center' },
    avatarText: { fontSize: 15, fontWeight: '700', color: '#fff' },
    cardInfo: { flex: 1 },
    nameRow: { flexDirection: 'row', alignItems: 'center', gap: 6, flexWrap: 'wrap' },
    cardName: { fontSize: 15, fontWeight: '600', color: colors.text },
    cardSub: { fontSize: 12, marginTop: 2, color: colors.textSecondary },
    roleChip: { flexDirection: 'row', alignItems: 'center', gap: 4 },
    rolePill: { paddingHorizontal: 7, paddingVertical: 2, borderRadius: 8 },
    rolePillText: { fontSize: 11, fontWeight: '600' },
    youBadge: { paddingHorizontal: 6, paddingVertical: 1, borderRadius: 6 },
    youBadgeText: { fontSize: 10, fontWeight: '700' },
    dirtyDot: { width: 7, height: 7, borderRadius: 4, backgroundColor: '#d97706' },

    expandedPanel: { paddingHorizontal: 14, paddingBottom: 14, paddingTop: 12, borderTopWidth: 1, borderTopColor: colors.border, gap: 12 },
    expandedLabel: { fontSize: 12, lineHeight: 16, color: colors.textSecondary },
    roleOptions: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
    roleOption: { paddingHorizontal: 14, paddingVertical: 8, borderRadius: 8, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.inputBackground },
    roleOptionText: { fontSize: 13, fontWeight: '600', color: colors.text },
    removeBtn: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 6, paddingVertical: 10, borderRadius: 8, borderWidth: 1, marginTop: 4, borderColor: COLORS.error, backgroundColor: colors.errorBackground },
    removeBtnText: { fontSize: 13, fontWeight: '600', color: COLORS.error },

    summaryRow: { flexDirection: 'row', gap: 10, marginBottom: 20 },
    summaryCard: { flex: 1, borderRadius: 12, padding: 12, alignItems: 'center', gap: 4, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.cardBackground, ...CARD_SHADOW },
    summaryValue: { fontSize: 14, fontWeight: '700', color: colors.text },
    summaryLabel: { fontSize: 11, textAlign: 'center', color: colors.textSecondary },

    hoursBreakdown: { flexDirection: 'row', borderRadius: 10, borderWidth: 1, borderColor: colors.border, overflow: 'hidden', marginBottom: 4 },
    hbItem: { flex: 1, alignItems: 'center', paddingVertical: 10, backgroundColor: colors.inputBackground },
    hbLabel: { fontSize: 11, marginBottom: 2, color: colors.textSecondary },
    hbVal: { fontSize: 14, fontWeight: '700', color: colors.text },
    hoursVal: { fontSize: 14, fontWeight: '600', color: colors.text },
    payVal: { fontSize: 12, color: colors.textSecondary },
    noHours: { fontSize: 12, color: colors.textSecondary },

    fieldRow: { flexDirection: 'row', alignItems: 'center', gap: 12 },
    fieldLabel: { width: 88, fontSize: 13, fontWeight: '500', color: colors.textSecondary },
    segRow: { flex: 1, flexDirection: 'row', flexWrap: 'wrap', gap: 6 },
    segBtn: { paddingHorizontal: 10, paddingVertical: 6, borderRadius: 8, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.inputBackground },
    segBtnText: { fontSize: 12, fontWeight: '500', color: colors.text },
    rateInputWrap: { flex: 1, flexDirection: 'row', alignItems: 'center', borderWidth: 1, borderColor: colors.border, borderRadius: 8, paddingHorizontal: 10, backgroundColor: colors.inputBackground },
    currencySymbol: { fontSize: 14, marginRight: 2, color: colors.textSecondary },
    rateInput: { flex: 1, fontSize: 14, paddingVertical: 8, color: colors.text },
    rateUnit: { fontSize: 12, marginLeft: 2, color: colors.textSecondary },
    notesInput: { flex: 1, borderWidth: 1, borderColor: colors.border, borderRadius: 8, padding: 10, fontSize: 13, minHeight: 72, textAlignVertical: 'top', color: colors.text, backgroundColor: colors.inputBackground },

    saveBtn: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 6, backgroundColor: colors.primary, borderRadius: 10, paddingVertical: 12, marginTop: 4 },
    saveBtnDisabled: { opacity: 0.4 },
    saveBtnText: { fontSize: 14, fontWeight: '700', color: '#fff' },

    inviteCard: { borderRadius: 14, borderWidth: 1, borderColor: colors.border, padding: 16, gap: 12, backgroundColor: colors.cardBackground, ...CARD_SHADOW },
    inviteCardTitle: { fontSize: 16, fontWeight: '700', color: colors.text },
    inviteCardSub: { fontSize: 13, lineHeight: 18, color: colors.textSecondary },
    codeBox: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', borderWidth: 1, borderColor: colors.border, borderRadius: 10, paddingHorizontal: 16, paddingVertical: 14, backgroundColor: colors.inputBackground },
    codeText: { fontSize: 26, fontWeight: '700', letterSpacing: 4, color: colors.text },
    copiedText: { fontSize: 12, fontWeight: '600', color: colors.primary },
    inviteActions: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
    inviteActionBtn: { flexDirection: 'row', alignItems: 'center', gap: 8, paddingVertical: 8, paddingHorizontal: 14, borderRadius: 8, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.inputBackground },
    inviteActionText: { fontSize: 14, fontWeight: '600', color: colors.text },
    emailForm: { borderRadius: 10, padding: 14, borderWidth: 1, borderColor: colors.border, gap: 8, backgroundColor: colors.inputBackground },
    emailFormTitle: { fontSize: 13, fontWeight: '600', color: colors.text },
    emailFormSub: { fontSize: 12, color: colors.textSecondary },
    emailInput: { borderWidth: 1, borderColor: colors.border, borderRadius: 8, paddingHorizontal: 12, paddingVertical: 10, fontSize: 14, color: colors.text, backgroundColor: colors.surface },
    emailFormActions: { flexDirection: 'row', gap: 8 },
    sendBtnWrap: { flex: 1, borderRadius: 8, overflow: 'hidden' },
    sendBtn: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 6, paddingVertical: 10, backgroundColor: colors.primary },
    sendBtnText: { fontSize: 14, fontWeight: '600', color: '#fff' },
    cancelBtn: { paddingHorizontal: 14, paddingVertical: 10, borderRadius: 8, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.inputBackground },
    cancelBtnText: { fontSize: 14, color: colors.textSecondary },
    noCodeContainer: { alignItems: 'center', paddingTop: 48 },
    noCodeText: { fontSize: 14, textAlign: 'center', color: colors.textSecondary },

    fab: {
      width: FAB.size,
      height: FAB.size,
      borderRadius: FAB.borderRadius,
      backgroundColor: colors.primary,
      alignItems: 'center',
      justifyContent: 'center',
      ...(FAB as any),
    },
  });
