import { StyleSheet } from 'react-native';
import { SPACING, CARD, CARD_SHADOW } from '@/constants/designSystem';

const getDynamicStyles = (colors: any, isDark: boolean, isWebDesktop = false) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.background,
    },
    header: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingHorizontal: SPACING.lg,
      paddingVertical: SPACING.md,
      backgroundColor: colors.surface,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: colors.border,
    },
    headerLeft: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: SPACING.sm,
    },
    greeting: {
      fontSize: 10,
      fontWeight: '700',
      color: colors.textSecondary,
      letterSpacing: 1.2,
      textTransform: 'uppercase',
    },
    welcomeText: {
      fontSize: 17,
      fontWeight: '700',
      color: colors.primary,
      marginTop: 1,
    },
    headerButtons: {
      flexDirection: 'row',
      gap: SPACING.sm,
    },
    headerButton: {
      width: 36,
      height: 36,
      borderRadius: 18,
      backgroundColor: colors.inputBackground,
      alignItems: 'center',
      justifyContent: 'center',
    },
    iconButton: {
      width: 36,
      height: 36,
      backgroundColor: colors.inputBackground,
      borderRadius: 18,
      alignItems: 'center',
      justifyContent: 'center',
    },
    content: {
      flex: 1,
      padding: SPACING.lg,
    },
    statsGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: SPACING.sm,
      marginBottom: SPACING.lg,
      ...(isWebDesktop ? { maxWidth: 680, alignSelf: 'center', width: '100%' } : {}),
    },
    statCard: {
      flex: 1,
      minWidth: '47%',
      backgroundColor: colors.cardBackground,
      borderRadius: CARD.borderRadius,
      padding: SPACING.md,
      ...CARD_SHADOW,
      borderWidth: CARD.borderWidth,
      borderColor: colors.border,
    },
    statValue: {
      fontSize: 28,
      fontWeight: '800',
      marginBottom: 2,
      letterSpacing: -0.5,
    },
    statLabel: {
      fontSize: 11,
      fontWeight: '600',
      color: colors.textSecondary,
      textTransform: 'uppercase',
      letterSpacing: 0.5,
    },
    sectionHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: SPACING.sm,
      ...(isWebDesktop ? { maxWidth: 680, alignSelf: 'center', width: '100%' } : {}),
    },
    sectionTitle: {
      fontSize: 12,
      fontWeight: '700',
      color: colors.textSecondary,
      letterSpacing: 1,
      textTransform: 'uppercase',
    },
    seeAllButton: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: SPACING.xs,
    },
    seeAllText: {
      fontSize: 12,
      color: colors.primary,
      fontWeight: '600',
    },
    jobCard: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.cardBackground,
      borderRadius: CARD.borderRadius,
      padding: SPACING.md,
      marginBottom: SPACING.sm,
      ...CARD_SHADOW,
      borderWidth: CARD.borderWidth,
      borderColor: colors.border,
      ...(isWebDesktop ? { maxWidth: 680, alignSelf: 'center', width: '100%' } : {}),
    },
    jobDot: {
      width: 8,
      height: 8,
      borderRadius: 4,
      marginRight: SPACING.md,
      flexShrink: 0,
    },
    jobDetails: {
      flex: 1,
    },
    jobTitle: {
      fontSize: 14,
      fontWeight: '600',
      color: colors.text,
    },
    jobMeta: {
      fontSize: 12,
      color: colors.textSecondary,
      marginTop: 2,
    },
    jobTime: {
      fontSize: 12,
      fontWeight: '600',
      color: colors.textSecondary,
    },
    emptyState: {
      alignItems: 'center',
      padding: SPACING.xxl,
      backgroundColor: colors.cardBackground,
      borderRadius: CARD.borderRadius,
      ...CARD_SHADOW,
      borderWidth: CARD.borderWidth,
      borderColor: colors.border,
      ...(isWebDesktop ? { maxWidth: 680, alignSelf: 'center', width: '100%' } : {}),
    },
    emptyStateText: {
      fontSize: 13,
      color: colors.textSecondary,
      marginTop: SPACING.md,
    },
    emptyStateButton: {
      marginTop: SPACING.lg,
      paddingHorizontal: SPACING.xl,
      paddingVertical: SPACING.md,
      backgroundColor: colors.primary,
      borderRadius: CARD.borderRadius,
    },
    emptyStateButtonText: {
      color: '#fff',
      fontWeight: '600',
      fontSize: 13,
    },
    cameraCard: {
      flexDirection: 'row',
      alignItems: 'center',
      padding: SPACING.md,
      marginTop: SPACING.md,
      borderRadius: CARD.borderRadius,
      backgroundColor: colors.cardBackground,
      ...CARD_SHADOW,
      borderWidth: CARD.borderWidth,
      borderColor: colors.border,
      ...(isWebDesktop ? { maxWidth: 680, alignSelf: 'center', width: '100%' } : {}),
    },
    cameraIconContainer: {
      width: 40,
      height: 40,
      borderRadius: 20,
      justifyContent: 'center',
      alignItems: 'center',
      marginRight: SPACING.md,
      backgroundColor: 'transparent',
      overflow: 'hidden',
    },
    cameraCardContent: {
      flex: 1,
    },
    cameraCardTitle: {
      fontSize: 14,
      fontWeight: '600',
      marginBottom: SPACING.xs,
      color: colors.text,
    },
    cameraCardSubtitle: {
      fontSize: 12,
      color: colors.textSecondary,
    },
  });

export default getDynamicStyles;
