import { Platform, StyleSheet } from 'react-native';
import { SPACING, TYPOGRAPHY, CARD, ICON, SEARCH_BAR, FAB, HEADER, ICON_BUTTON, COLORS, CARD_SHADOW } from '@/constants/designSystem';

const getDynamicStyles = (colors: any) =>
  StyleSheet.create({
    container: { flex: 1, backgroundColor: colors.background },
    header: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingHorizontal: HEADER.paddingHorizontal,
      paddingVertical: HEADER.paddingVertical,
      backgroundColor: colors.surface,
    },
    headerLeft: { flexDirection: 'row', alignItems: 'center', gap: SPACING.md },
    headerTitle: { fontSize: TYPOGRAPHY.screenTitle.fontSize, fontWeight: TYPOGRAPHY.screenTitle.fontWeight, color: COLORS.brand, position: 'absolute', left: 0, right: 0, textAlign: 'center' },
    headerSubtitle: { fontSize: TYPOGRAPHY.body.fontSize, color: colors.textSecondary, marginTop: SPACING.xs },
    headerButtons: { flexDirection: 'row', gap: SPACING.md },
    headerButton: { padding: SPACING.sm },
    iconButton: {
      width: ICON_BUTTON.size,
      height: ICON_BUTTON.size,
      backgroundColor: colors.inputBackground,
      borderRadius: ICON_BUTTON.borderRadius,
      borderWidth: ICON_BUTTON.borderWidth,
      borderColor: CARD.borderColor,
      alignItems: 'center',
      justifyContent: 'center',
    },
    tabContainer: {
      flexDirection: 'row',
      backgroundColor: colors.surface,
      paddingHorizontal: SPACING.lg,
      paddingBottom: SPACING.md,
      gap: SPACING.md,
    },
    tab: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: SPACING.md,
      borderRadius: CARD.borderRadius,
      backgroundColor: colors.cardBackground,
      gap: SPACING.sm,
    },
    activeTab: { backgroundColor: colors.primaryLight },
    tabText: { fontSize: TYPOGRAPHY.body.fontSize, fontWeight: TYPOGRAPHY.heading.fontWeight, color: colors.textSecondary },
    activeTabText: { color: colors.primary },
    searchContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.inputBackground,
      marginHorizontal: SPACING.lg,
      marginTop: SPACING.md,
      marginBottom: SPACING.xs,
      paddingHorizontal: SEARCH_BAR.paddingHorizontal,
      paddingVertical: SEARCH_BAR.paddingVertical,
      borderRadius: SEARCH_BAR.borderRadius,
      gap: SPACING.sm,
    },
    searchInput: { flex: 1, fontSize: TYPOGRAPHY.body.fontSize, color: colors.text, padding: 0, margin: 0, borderWidth: 0, backgroundColor: 'transparent', ...(Platform.OS === 'web' ? { outlineStyle: 'none' } : {}) } as any,
    filterContainer: {
      paddingHorizontal: SPACING.lg,
      paddingTop: SPACING.sm,
      paddingBottom: SPACING.xs,
    },
    list: { padding: SPACING.lg, paddingBottom: 100 },
    card: {
      backgroundColor: colors.cardBackground,
      borderRadius: CARD.borderRadius,
      padding: SPACING.md,
      marginBottom: SPACING.sm,
      ...CARD_SHADOW,
      borderWidth: CARD.borderWidth,
      borderColor: CARD.borderColor,
    },
    cardHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: SPACING.sm },
    cardNumber: { fontSize: TYPOGRAPHY.headingMedium.fontSize, fontWeight: '700', color: colors.text },
    cardClient: { fontSize: TYPOGRAPHY.body.fontSize, color: colors.textSecondary, marginTop: 2 },
    statusContainer: { flexDirection: 'column', gap: SPACING.xs, alignItems: 'flex-end' },
    statusBadge: { paddingHorizontal: SPACING.sm, paddingVertical: 3, borderRadius: 6 },
    statusText: { fontSize: 10, fontWeight: '700' },
    cardFooter: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginTop: SPACING.xs },
    cardDate: { fontSize: TYPOGRAPHY.label.fontSize, color: colors.textSecondary },
    totalContainer: { flexDirection: 'row', alignItems: 'center', gap: SPACING.sm },
    paidIndicator: { fontSize: TYPOGRAPHY.caption.fontSize, fontWeight: TYPOGRAPHY.heading.fontWeight },
    cardTotal: { fontSize: TYPOGRAPHY.headingMedium.fontSize, fontWeight: '700', color: colors.primary },
    fab: {
      position: 'absolute',
      right: SPACING.xl,
      bottom: SPACING.xl,
      width: FAB.size,
      height: FAB.size,
      borderRadius: FAB.borderRadius,
      backgroundColor: colors.primary,
      justifyContent: 'center',
      alignItems: 'center',
      ...(FAB as any),
    },
    emptyContainer: { alignItems: 'center', justifyContent: 'center', paddingTop: SPACING.xxl * 2 },
    emptyText: { fontSize: TYPOGRAPHY.heading.fontSize, fontWeight: TYPOGRAPHY.heading.fontWeight, color: colors.textSecondary, marginBottom: SPACING.sm },
    emptySubtext: { fontSize: TYPOGRAPHY.body.fontSize, color: colors.textSecondary, textAlign: 'center' },
    quickActions: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: SPACING.xs,
      marginBottom: SPACING.xs,
    },
    quickActionButton: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: SPACING.sm,
      paddingVertical: SPACING.xs,
      borderRadius: SPACING.md,
      gap: SPACING.xs,
    },
    quickActionText: {
      fontSize: TYPOGRAPHY.caption.fontSize,
      fontWeight: TYPOGRAPHY.heading.fontWeight,
    },
    paymentMethodBadge: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: SPACING.sm,
      paddingVertical: SPACING.xs,
      borderRadius: SPACING.md,
      gap: SPACING.xs,
    },
    paymentMethodText: {
      fontSize: TYPOGRAPHY.caption.fontSize,
      fontWeight: TYPOGRAPHY.heading.fontWeight,
      textTransform: 'capitalize',
    },
    paymentModalOverlay: {
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      backgroundColor: 'rgba(0,0,0,0.5)',
      justifyContent: 'center',
      alignItems: 'center',
      padding: SPACING.xl,
    },
    paymentModal: {
      borderRadius: SPACING.lg,
      padding: SPACING.xl,
      width: '100%',
      maxWidth: 400,
    },
    paymentModalTitle: {
      fontSize: TYPOGRAPHY.heading.fontSize + 2,
      fontWeight: '700',
      marginBottom: SPACING.xs,
    },
    paymentModalSubtitle: {
      fontSize: TYPOGRAPHY.body.fontSize,
      marginBottom: SPACING.xl,
    },
    paymentModalLabel: {
      fontSize: TYPOGRAPHY.body.fontSize,
      fontWeight: TYPOGRAPHY.heading.fontWeight,
      marginBottom: SPACING.md,
    },
    paymentOption: {
      flexDirection: 'row',
      alignItems: 'center',
      padding: SPACING.lg,
      borderRadius: CARD.borderRadius,
      borderWidth: 1,
      marginBottom: SPACING.md,
      gap: SPACING.md,
    },
    paymentOptionText: {
      fontSize: TYPOGRAPHY.headingMedium.fontSize,
      fontWeight: TYPOGRAPHY.bodyMedium.fontWeight,
    },
    paymentCancelButton: {
      padding: SPACING.lg,
      borderRadius: SPACING.sm,
      borderWidth: 1,
      alignItems: 'center',
      marginTop: SPACING.sm,
    },
    paymentCancelText: {
      fontSize: TYPOGRAPHY.headingMedium.fontSize,
      fontWeight: TYPOGRAPHY.heading.fontWeight,
    },
    statusFilterContainer: {
      flexDirection: 'row',
      paddingHorizontal: SPACING.lg,
      paddingBottom: SPACING.md,
      gap: SPACING.sm,
    },
    statusFilterButton: {
      paddingHorizontal: SPACING.lg,
      paddingVertical: SPACING.sm,
      borderRadius: 20,
      backgroundColor: colors.inputBackground,
      borderWidth: 1,
      borderColor: CARD.borderColor,
    },
    statusFilterButtonActive: {
      backgroundColor: colors.primary,
      borderColor: colors.primary,
    },
    statusFilterText: {
      fontSize: TYPOGRAPHY.body.fontSize,
      fontWeight: TYPOGRAPHY.heading.fontWeight,
      color: colors.textSecondary,
    },
    statusFilterTextActive: {
      color: '#FFFFFF',
    },
  });
export default getDynamicStyles;
