import { Platform, StyleSheet } from 'react-native';
import { SPACING, TYPOGRAPHY, CARD, ICON, SEARCH_BAR, FAB, HEADER, ICON_BUTTON, COLORS, CARD_SHADOW } from '@/constants/designSystem';

const getDynamicStyles = (colors: any) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.background,
    },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: HEADER.paddingHorizontal,
      paddingVertical: HEADER.paddingVertical,
      backgroundColor: colors.surface,
    },
    headerLeft: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: SPACING.md,
    },
    headerTitle: {
      fontSize: TYPOGRAPHY.screenTitle.fontSize,
      fontWeight: TYPOGRAPHY.screenTitle.fontWeight,
      color: COLORS.brand,
      position: 'absolute',
      left: 0,
      right: 0,
      textAlign: 'center',
    },
    headerSubtitle: {
      fontSize: TYPOGRAPHY.caption.fontSize,
      fontWeight: TYPOGRAPHY.caption.fontWeight,
      color: colors.textSecondary,
      marginTop: SPACING.xs,
    },
    tabContainer: {
      flexDirection: 'row',
      backgroundColor: colors.surface,
      paddingHorizontal: SPACING.lg,
      paddingBottom: SPACING.md,
      gap: SPACING.md,
      zIndex: 1000,
      elevation: 5,
    },
    tab: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: SPACING.sm,
      paddingVertical: SPACING.md,
      borderRadius: CARD.borderRadius,
      backgroundColor: colors.cardBackground,
    },
    activeTab: {
      backgroundColor: colors.primaryLight,
    },
    tabText: {
      fontSize: TYPOGRAPHY.body.fontSize,
      fontWeight: TYPOGRAPHY.bodyMedium.fontWeight,
      color: colors.textSecondary,
    },
    activeTabText: {
      color: colors.primary,
      fontWeight: TYPOGRAPHY.heading.fontWeight,
    },
    content: {
      flex: 1,
    },
    section: {
      padding: SPACING.lg,
    },
    noteCard: {
      backgroundColor: colors.cardBackground,
      borderRadius: CARD.borderRadius,
      padding: CARD.padding,
      marginBottom: SPACING.md,
      ...CARD_SHADOW,
      borderWidth: CARD.borderWidth,
      borderColor: CARD.borderColor,
      zIndex: 0,
      elevation: 0,
    },
    noteHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: SPACING.sm,
    },
    noteTitle: {
      fontSize: TYPOGRAPHY.heading.fontSize,
      fontWeight: TYPOGRAPHY.heading.fontWeight,
      color: colors.text,
      lineHeight: TYPOGRAPHY.heading.lineHeight,
      flex: 1,
      marginRight: SPACING.md,
    },
    noteContent: {
      fontSize: TYPOGRAPHY.body.fontSize,
      color: COLORS.text.secondary,
      lineHeight: TYPOGRAPHY.body.lineHeight,
      marginBottom: SPACING.sm,
    },
    noteDate: {
      fontSize: TYPOGRAPHY.caption.fontSize,
      color: COLORS.text.secondary,
    },
    todoInputContainer: {
      flexDirection: 'row',
      gap: SPACING.md,
      marginBottom: SPACING.lg,
    },
    todoInput: {
      flex: 1,
      backgroundColor: colors.cardBackground,
      borderRadius: CARD.borderRadius,
      paddingHorizontal: SPACING.lg,
      paddingVertical: SPACING.md,
      fontSize: TYPOGRAPHY.headingMedium.fontSize,
      color: colors.text,
      borderWidth: CARD.borderWidth,
      borderColor: colors.border,
    },
    addTodoButton: {
      width: 48,
      height: 48,
      borderRadius: CARD.borderRadius,
      backgroundColor: colors.primary,
      justifyContent: 'center',
      alignItems: 'center',
    },
    addTodoButtonDisabled: {
      opacity: 0.5,
    },
    todoItem: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.cardBackground,
      borderRadius: CARD.borderRadius,
      padding: SPACING.md,
      marginBottom: SPACING.sm,
      gap: SPACING.md,
      zIndex: 0,
      elevation: 0,
    },
    todoCheckbox: {
      padding: 2,
    },
    todoText: {
      flex: 1,
      fontSize: TYPOGRAPHY.headingMedium.fontSize,
      color: colors.text,
    },
    todoTextCompleted: {
      textDecorationLine: 'line-through',
      color: colors.textSecondary,
    },
    fab: {
      position: 'absolute',
      right: SPACING.xl,
      bottom: SPACING.xl,
      width: FAB.size,
      height: FAB.size,
      borderRadius: FAB.borderRadius,
      backgroundColor: colors.primary,
      justifyContent: 'center',
      alignItems: 'center',
      ...(FAB as any),
    },
    emptyContainer: {
      alignItems: 'center',
      justifyContent: 'center',
      paddingTop: SPACING.xxl * 2,
    },
    emptyText: {
      fontSize: TYPOGRAPHY.heading.fontSize,
      fontWeight: TYPOGRAPHY.heading.fontWeight,
      color: colors.textSecondary,
      marginTop: SPACING.lg,
      marginBottom: SPACING.sm,
    },
    emptySubtext: {
      fontSize: TYPOGRAPHY.body.fontSize,
      color: colors.textSecondary,
      textAlign: 'center',
    },
    modalContainer: {
      flex: 1,
      backgroundColor: colors.background,
    },
    modalHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingHorizontal: HEADER.paddingHorizontal,
      paddingVertical: HEADER.paddingVertical,
      backgroundColor: colors.surface,
    },
    modalTitle: {
      fontSize: TYPOGRAPHY.heading.fontSize,
      fontWeight: TYPOGRAPHY.heading.fontWeight,
      color: colors.text,
    },
    noteTitleInput: {
      fontSize: TYPOGRAPHY.screenTitle.fontSize,
      fontWeight: TYPOGRAPHY.heading.fontWeight,
      color: colors.text,
      padding: SPACING.lg,
      paddingBottom: SPACING.sm,
    },
    noteContentInput: {
      flex: 1,
      fontSize: TYPOGRAPHY.headingMedium.fontSize,
      color: colors.text,
      padding: SPACING.lg,
      paddingTop: SPACING.sm,
      lineHeight: 24,
    },
    teamNoteCard: {
      backgroundColor: colors.cardBackground,
      borderRadius: CARD.borderRadius,
      padding: CARD.padding,
      marginBottom: SPACING.md,
      ...CARD_SHADOW,
      borderWidth: CARD.borderWidth,
      borderColor: 'rgba(27, 77, 110, 0.12)',
      borderLeftWidth: 4,
      borderLeftColor: colors.primary,
      zIndex: 0,
      elevation: 0,
    },
    teamNoteAuthor: {
      fontSize: TYPOGRAPHY.caption.fontSize,
      fontWeight: '600',
      color: colors.primary,
      textTransform: 'uppercase',
      letterSpacing: 0.5,
      marginBottom: SPACING.xs,
    },
    teamNoteBadge: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: SPACING.xs,
      backgroundColor: 'rgba(27, 77, 110, 0.08)',
      paddingHorizontal: SPACING.sm,
      paddingVertical: SPACING.xs,
      borderRadius: 6,
      alignSelf: 'flex-start',
      marginBottom: SPACING.sm,
    },
    teamNoteBadgeText: {
      fontSize: 11,
      fontWeight: '600',
      color: colors.primary,
    },
    teamNoteFooter: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginTop: SPACING.sm,
    },
    sendingIndicator: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: SPACING.sm,
      padding: SPACING.md,
      backgroundColor: 'rgba(27, 77, 110, 0.06)',
      borderRadius: CARD.borderRadius,
      marginBottom: SPACING.md,
    },
    sendingText: {
      fontSize: TYPOGRAPHY.body.fontSize,
      color: colors.primary,
      fontWeight: TYPOGRAPHY.bodyMedium.fontWeight,
    },
    moreGrid: {
      gap: SPACING.lg,
      paddingHorizontal: SPACING.lg,
      paddingVertical: SPACING.sm,
    },
    moreCard: {
      backgroundColor: colors.surface,
      borderRadius: CARD.borderRadius,
      padding: SPACING.xl,
      ...CARD_SHADOW,
      borderWidth: CARD.borderWidth,
      borderColor: CARD.borderColor,
      position: 'relative',
    },
    moreIconContainer: {
      width: FAB.size,
      height: FAB.size,
      borderRadius: SPACING.lg,
      backgroundColor: colors.primary + '15',
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: SPACING.lg,
    },
    moreCardTitle: {
      fontSize: TYPOGRAPHY.heading.fontSize,
      fontWeight: '700',
      color: colors.text,
      marginBottom: SPACING.sm,
    },
    moreCardDescription: {
      fontSize: TYPOGRAPHY.body.fontSize,
      color: colors.textSecondary,
      lineHeight: TYPOGRAPHY.body.lineHeight,
      marginBottom: SPACING.md,
    },
    moreCardArrow: {
      position: 'absolute',
      top: SPACING.xl,
      right: SPACING.xl,
    },
    dropdown: {
      position: 'absolute',
      top: '100%',
      right: 0,
      backgroundColor: colors.surface,
      borderRadius: CARD.borderRadius,
      marginTop: SPACING.sm,
      minWidth: 200,
      ...CARD_SHADOW,
      borderWidth: CARD.borderWidth,
      borderColor: CARD.borderColor,
      zIndex: 10000,
      elevation: 15,
    },
    dropdownItem: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: SPACING.md,
      padding: SPACING.lg,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
    },
    dropdownItemText: {
      flex: 1,
      fontSize: TYPOGRAPHY.body.fontSize,
      fontWeight: TYPOGRAPHY.bodyMedium.fontWeight,
      color: colors.text,
    },
    dropdownDivider: {
      height: 1,
      backgroundColor: colors.border,
    },
  });

export default getDynamicStyles;
