import { StyleSheet, Platform } from 'react-native';

export const scheduleModalStyles = StyleSheet.create({
  container: {
    flex: 1,
  },
  overlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.4)',
    justifyContent: 'flex-end',
  },
  modal: {
    backgroundColor: '#fff',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    maxHeight: '90%',
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 24,
    paddingVertical: 18,
    borderBottomWidth: 1,
    borderBottomColor: '#f1f5f9',
  },
  headerTitleContainer: {
    flex: 1,
    marginRight: 12,
  },
  title: {
    fontSize: 18,
    fontWeight: '700',
    color: '#0f172a',
    letterSpacing: -0.3,
  },
  headerSubtitle: {
    fontSize: 12,
    color: '#94a3b8',
    marginTop: 2,
  },
  form: {
    padding: 24,
  },
  row: {
    flexDirection: 'row',
    gap: 16,
  },
  flex1: {
    flex: 1,
  },
  inputGroup: {
    marginBottom: 16,
  },
  label: {
    fontSize: 11,
    fontWeight: '600',
    color: '#64748b',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    marginBottom: 6,
  },
  input: {
    backgroundColor: '#f8fafc',
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 10,
    fontSize: 14,
    color: '#0f172a',
    borderWidth: 1,
    borderColor: '#e2e8f0',
  },
  textArea: {
    minHeight: 100,
    textAlignVertical: 'top',
  },
  picker: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#f8fafc',
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderWidth: 1,
    borderColor: '#e2e8f0',
  },
  pickerText: {
    fontSize: 14,
    color: '#0f172a',
    fontWeight: '500',
  },
  placeholderText: {
    color: '#94a3b8',
    fontWeight: '400',
  },
  dateTimeRow: {
    flexDirection: 'row',
    marginBottom: 24,
  },
  dateTimeColumn: {
    flex: 1,
  },
  dateTimeDivider: {
    width: 1,
    backgroundColor: '#e2e8f0',
    marginHorizontal: 16,
    marginVertical: 4,
  },
  dateTimeLabel: {
    fontSize: 11,
    fontWeight: '600',
    color: '#94a3b8',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    marginBottom: 8,
  },
  dateTimeTouchable: {
    paddingVertical: 6,
  },
  dateTimeValue: {
    fontSize: 16,
    fontWeight: '500',
    color: '#0f172a',
  },
  dateTimeValuePlaceholder: {
    color: '#cbd5e1',
  },
  timePickerButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: '#f8fafc',
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderWidth: 1,
    borderColor: '#e2e8f0',
  },
  timePickerButtonText: {
    fontSize: 14,
    color: '#0f172a',
  },
  pickerList: {
    marginTop: 6,
    backgroundColor: '#fff',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#e2e8f0',
    maxHeight: 240,
    ...Platform.select({
      web: {
        boxShadow: '0 4px 16px rgba(0,0,0,0.08)',
      },
      default: {
        elevation: 4,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.08,
        shadowRadius: 8,
      },
    }),
  },
  clientSearchContainer: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    paddingHorizontal: 14,
    paddingVertical: 10,
    gap: 8,
  },
  clientSearchInput: {
    flex: 1,
    fontSize: 14,
    color: '#0f172a',
    paddingVertical: 4,
  },
  pickerItem: {
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#f1f5f9',
  },
  pickerItemText: {
    fontSize: 14,
    color: '#334155',
  },
  pickerItemSubtext: {
    fontSize: 12,
    color: '#94a3b8',
    marginTop: 2,
  },
  addNewClientItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: '#f0f9ff',
  },
  addNewClientText: {
    fontSize: 15,
    color: '#0284c7',
    fontWeight: '600',
  },
  clientDetails: {
    marginTop: 12,
    padding: 14,
    backgroundColor: '#f8fafc',
    borderRadius: 12,
    gap: 8,
  },
  clientDetailRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  clientDetailText: {
    fontSize: 13,
    color: '#64748b',
    flex: 1,
  },
  addressSelectorSection: {
    marginTop: 12,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: '#f1f5f9',
  },
  addressSelectorLabel: {
    fontSize: 11,
    fontWeight: '700',
    color: '#64748b',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    marginBottom: 8,
  },
  addressSelectorRow: {
    flexDirection: 'row',
    marginBottom: 6,
  },
  addressToggleChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 20,
    marginRight: 8,
    backgroundColor: '#f1f5f9',
    borderWidth: 1.5,
    borderColor: '#e2e8f0',
  },
  addressToggleChipActive: {
    backgroundColor: '#1B4D6E',
    borderColor: '#1B4D6E',
  },
  addressToggleChipText: {
    fontSize: 11,
    fontWeight: '600',
    color: '#475569',
  },
  addressToggleChipTextActive: {
    color: '#fff',
  },
  primaryDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#cbd5e1',
  },
  primaryDotActive: {
    backgroundColor: 'rgba(255,255,255,0.6)',
  },
  selectedAddressText: {
    fontSize: 15,
    color: '#1B4D6E',
    marginTop: 6,
    lineHeight: 20,
    fontWeight: '500',
  },
  selectedAddressClickable: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginTop: 4,
    paddingVertical: 4,
    paddingHorizontal: 6,
    borderRadius: 6,
    backgroundColor: 'rgba(27,77,110,0.06)',
  },
  selectedAddressTextClickable: {
    flex: 1,
    fontSize: 12,
    color: '#1B4D6E',
    lineHeight: 16,
    textDecorationLine: 'underline',
  },
  clickableAddressRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 0,
  },
  clickableAddressInput: {
    flex: 1,
    borderTopRightRadius: 0,
    borderBottomRightRadius: 0,
    borderRightWidth: 0,
  },
  openMapsBtn: {
    height: 48,
    width: 48,
    borderTopRightRadius: 12,
    borderBottomRightRadius: 12,
    overflow: 'hidden' as const,
  },
  openMapsBtnGradient: {
    height: 48,
    width: 48,
    borderTopRightRadius: 12,
    borderBottomRightRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  multiAddressSection: {
    marginTop: 10,
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: '#f1f5f9',
    gap: 8,
  },
  extraAddressRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#f8fafc',
    borderRadius: 10,
    padding: 12,
    borderWidth: 1,
    borderColor: '#e2e8f0',
  },
  extraAddressInfo: {
    flex: 1,
    gap: 4,
  },
  travelTimeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  travelTimeText: {
    fontSize: 11,
    color: '#f59e0b',
    fontWeight: '600',
  },
  extraAddressChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
  },
  extraAddressLabel: {
    fontSize: 13,
    fontWeight: '600',
    color: '#1B4D6E',
  },
  extraAddressPaneCount: {
    fontSize: 12,
    color: '#64748b',
    marginLeft: 4,
  },
  addAddressRow: {
    gap: 6,
  },
  addAddressHint: {
    fontSize: 12,
    color: '#64748b',
    fontWeight: '500',
  },
  addAddressChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 16,
    marginRight: 8,
    backgroundColor: '#f0f9ff',
    borderWidth: 1,
    borderColor: '#bae6fd',
  },
  addAddressChipText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#0284c7',
  },
  travelSummaryRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: '#fffbeb',
    borderRadius: 10,
    padding: 10,
    borderWidth: 1,
    borderColor: '#fde68a',
  },
  travelSummaryText: {
    fontSize: 12,
    color: '#92400e',
    fontWeight: '500',
    flex: 1,
  },
  footer: {
    flexDirection: 'row',
    gap: 12,
    paddingHorizontal: 24,
    paddingVertical: 16,
    borderTopWidth: 1,
    borderTopColor: '#f1f5f9',
    backgroundColor: '#fff',
  },
  deleteButton: {
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderRadius: 12,
    backgroundColor: '#fef2f2',
    borderWidth: 1,
    borderColor: '#fecaca',
    alignItems: 'center',
    justifyContent: 'center',
  },
  cancelButton: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#e2e8f0',
    backgroundColor: '#fff',
    alignItems: 'center',
  },
  cancelButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#64748b',
  },
  saveButton: {
    flex: 1,
    borderRadius: 8,
    overflow: 'hidden' as const,
    alignItems: 'center',
  },
  saveButtonSolid: {
    backgroundColor: '#1B4D6E',
    paddingVertical: 14,
    justifyContent: 'center',
  },
  saveButtonGradient: {
    width: '100%',
    paddingVertical: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  saveButtonDisabled: {
    opacity: 0.5,
  },
  saveButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#fff',
  },
  errorContainer: {
    backgroundColor: '#fef2f2',
    padding: 12,
    marginHorizontal: 24,
    marginTop: 12,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#fecaca',
  },
  errorText: {
    color: '#dc2626',
    fontSize: 13,
    textAlign: 'center',
  },
  notifyPromptOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0,0,0,0.4)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  notifyPrompt: {
    backgroundColor: '#fff',
    borderRadius: 20,
    padding: 28,
    alignItems: 'center',
    width: '100%',
    maxWidth: 340,
  },
  notifyPromptTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#0f172a',
    marginTop: 12,
    marginBottom: 8,
  },
  notifyPromptText: {
    fontSize: 14,
    color: '#64748b',
    textAlign: 'center',
    marginBottom: 20,
    lineHeight: 20,
  },
  notificationOptions: {
    width: '100%',
    marginBottom: 20,
    gap: 10,
  },
  notificationOption: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingVertical: 14,
    paddingHorizontal: 16,
    backgroundColor: '#f8fafc',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#e2e8f0',
  },
  checkbox: {
    width: 22,
    height: 22,
    borderRadius: 6,
    borderWidth: 2,
    borderColor: '#1B4D6E',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#fff',
  },
  checkboxChecked: {
    backgroundColor: '#1B4D6E',
    borderColor: '#1B4D6E',
  },
  checkmark: {
    color: '#fff',
    fontSize: 14,
    fontWeight: 'bold',
  },
  notificationOptionText: {
    flex: 1,
    fontSize: 14,
    color: '#334155',
    fontWeight: '500',
  },
  notifyPromptButtons: {
    flexDirection: 'row',
    gap: 12,
    width: '100%',
  },
  notifyPromptButtonSecondary: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#e2e8f0',
    alignItems: 'center',
  },
  notifyPromptButtonSecondaryText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#64748b',
  },
  notifyPromptButtonPrimary: {
    flex: 1,
    borderRadius: 12,
    overflow: 'hidden' as const,
    alignItems: 'center',
  },
  notifyPromptButtonPrimaryGradient: {
    width: '100%',
    paddingVertical: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  notifyPromptButtonPrimaryText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#fff',
  },
  recurringToggle: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingVertical: 10,
    paddingHorizontal: 14,
    backgroundColor: '#f8fafc',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#e2e8f0',
  },
  recurringToggleText: {
    fontSize: 14,
    color: '#64748b',
    fontWeight: '500',
  },
  recurringToggleTextActive: {
    color: '#0284c7',
  },
  recurringOptions: {
    marginTop: 12,
    padding: 16,
    backgroundColor: '#f8fafc',
    borderRadius: 12,
    gap: 16,
  },
  recurrenceTypeRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  recurrenceTypeButton: {
    paddingVertical: 8,
    paddingHorizontal: 14,
    borderRadius: 20,
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#e2e8f0',
  },
  recurrenceTypeButtonActive: {
    backgroundColor: '#1B4D6E',
    borderColor: '#1B4D6E',
  },
  recurrenceTypeButtonText: {
    fontSize: 13,
    color: '#64748b',
    fontWeight: '500',
  },
  recurrenceTypeButtonTextActive: {
    color: '#fff',
  },
  customRecurrenceOptions: {
    gap: 12,
  },
  subLabel: {
    fontSize: 11,
    fontWeight: '600',
    color: '#64748b',
    textTransform: 'uppercase',
    letterSpacing: 0.3,
  },
  weekOfMonthRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  weekOfMonthButton: {
    paddingVertical: 7,
    paddingHorizontal: 12,
    borderRadius: 16,
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#e2e8f0',
  },
  weekOfMonthButtonActive: {
    backgroundColor: '#1B4D6E',
    borderColor: '#1B4D6E',
  },
  weekOfMonthButtonText: {
    fontSize: 12,
    color: '#64748b',
    fontWeight: '500',
  },
  weekOfMonthButtonTextActive: {
    color: '#fff',
  },
  daysOfWeekRow: {
    flexDirection: 'row',
    gap: 6,
  },
  dayButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#e2e8f0',
    alignItems: 'center',
    justifyContent: 'center',
  },
  dayButtonActive: {
    backgroundColor: '#1B4D6E',
    borderColor: '#1B4D6E',
  },
  dayButtonText: {
    fontSize: 12,
    color: '#64748b',
    fontWeight: '500',
  },
  dayButtonTextActive: {
    color: '#fff',
  },
  monthlyOptions: {
    gap: 8,
  },
  monthGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    marginBottom: 8,
  },
  monthButton: {
    paddingVertical: 8,
    paddingHorizontal: 10,
    borderRadius: 10,
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#e2e8f0',
    minWidth: 52,
    alignItems: 'center' as const,
  },
  monthButtonActive: {
    backgroundColor: '#1B4D6E',
    borderColor: '#1B4D6E',
  },
  monthButtonText: {
    fontSize: 13,
    color: '#64748b',
    fontWeight: '500' as const,
  },
  monthButtonTextActive: {
    color: '#fff',
  },
  smallInput: {
    width: 80,
  },
  endDateRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  jobTypeFilterRow: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    backgroundColor: '#f0f9ff',
    borderBottomWidth: 1,
    borderBottomColor: '#e0f2fe',
  },
  jobTypeFilterLabel: {
    fontSize: 12,
    color: '#0284c7',
    fontStyle: 'italic',
  },
  somethingElseButton: {
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderTopWidth: 1,
    borderTopColor: '#f1f5f9',
    alignItems: 'center',
  },
  somethingElseText: {
    fontSize: 14,
    color: '#0284c7',
    fontWeight: '500',
  },
  addressExpandToggle: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingVertical: 6,
  },
  addressExpandText: {
    fontSize: 13,
    color: '#0284c7',
    fontWeight: '500',
  },
  addressExpandHint: {
    fontSize: 12,
    color: '#94a3b8',
    flex: 1,
    marginLeft: 4,
  },
  paymentSection: {
    marginTop: 8,
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: '#f1f5f9',
  },
  paymentAmountRow: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    alignItems: 'flex-end',
    marginBottom: 16,
  },
  paymentAmountField: {
    width: '50%',
    maxWidth: 200,
  },
  creditBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#f0fdf4',
    borderWidth: 1,
    borderColor: '#bbf7d0',
    borderRadius: 12,
    padding: 14,
    marginBottom: 16,
  },
  creditBannerActive: {
    backgroundColor: '#dcfce7',
    borderColor: '#22c55e',
  },
  creditBannerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    flex: 1,
  },
  creditCheckbox: {
    width: 20,
    height: 20,
    borderRadius: 6,
    borderWidth: 2,
    borderColor: '#22c55e',
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    backgroundColor: '#fff',
  },
  creditCheckboxChecked: {
    backgroundColor: '#22c55e',
    borderColor: '#22c55e',
  },
  creditBannerTitle: {
    fontSize: 13,
    fontWeight: '700' as const,
    color: '#166534',
  },
  creditBannerSub: {
    fontSize: 12,
    color: '#16a34a',
    marginTop: 1,
  },
  creditBannerAmount: {
    fontSize: 15,
    fontWeight: '700' as const,
    color: '#166534',
  },
  paymentHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 12,
  },
  priceOverrideBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    marginTop: 4,
    backgroundColor: '#e8f0f6',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 8,
    alignSelf: 'flex-start',
  },
  priceOverrideBadgeText: {
    fontSize: 11,
    color: '#1B4D6E',
    fontWeight: '600',
  },
  paymentHeaderText: {
    fontSize: 11,
    fontWeight: '600',
    color: '#64748b',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  paymentStatusRow: {
    flexDirection: 'row',
    gap: 8,
  },
  paymentStatusButton: {
    flex: 1,
    paddingVertical: 9,
    paddingHorizontal: 10,
    borderRadius: 10,
    backgroundColor: '#f8fafc',
    borderWidth: 1,
    borderColor: '#e2e8f0',
    alignItems: 'center',
  },
  paymentStatusButtonActive: {
    backgroundColor: '#fef2f2',
    borderColor: '#fca5a5',
  },
  paymentStatusButtonPaid: {
    backgroundColor: '#f0fdf4',
    borderColor: '#86efac',
  },
  paymentStatusButtonPartial: {
    backgroundColor: '#fffbeb',
    borderColor: '#fcd34d',
  },
  paymentStatusButtonText: {
    fontSize: 13,
    fontWeight: '500',
    color: '#64748b',
  },
  paymentStatusButtonTextActive: {
    color: '#0f172a',
    fontWeight: '600',
  },
  paymentMethodRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  paymentMethodButton: {
    paddingVertical: 9,
    paddingHorizontal: 14,
    borderRadius: 20,
    backgroundColor: '#f8fafc',
    borderWidth: 1,
    borderColor: '#e2e8f0',
  },
  paymentMethodButtonActive: {
    backgroundColor: '#1B4D6E',
    borderColor: '#1B4D6E',
  },
  paymentMethodButtonText: {
    fontSize: 13,
    fontWeight: '500',
    color: '#64748b',
  },
  paymentMethodButtonTextActive: {
    color: '#fff',
  },
  labelRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 8,
  },
  coordinatesRow: {
    flexDirection: 'row',
    gap: 16,
    marginBottom: 24,
  },
  jobTypeRate: {
    fontSize: 12,
    color: '#94a3b8',
    marginTop: 2,
  },
  estimatedCostContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginTop: 10,
    paddingHorizontal: 14,
    paddingVertical: 10,
    backgroundColor: '#f0fdf4',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#bbf7d0',
  },
  estimatedCostText: {
    fontSize: 13,
    color: '#16a34a',
    fontWeight: '600',
  },
  unitDurationInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginTop: 8,
    paddingHorizontal: 14,
    paddingVertical: 10,
    backgroundColor: '#f0f9ff',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#bae6fd',
  },
  unitDurationText: {
    fontSize: 13,
    color: '#0284c7',
    fontWeight: '500',
  },
  crewSizeContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 16,
    paddingVertical: 10,
    backgroundColor: '#f8fafc',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#e2e8f0',
  },
  crewButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    overflow: 'hidden' as const,
  },
  crewButtonGradient: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
  },
  crewButtonDisabled: {
    opacity: 0.6,
  },
  crewButtonText: {
    fontSize: 20,
    color: '#fff',
    fontWeight: '600',
  },
  crewSizeDisplay: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    minWidth: 90,
    justifyContent: 'center',
  },
  crewSizeText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#1B4D6E',
  },
  predictionLoading: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginTop: 12,
    padding: 14,
    backgroundColor: '#f0f9ff',
    borderRadius: 10,
  },
  predictionLoadingText: {
    fontSize: 13,
    color: '#0284c7',
  },
  predictionContainer: {
    marginTop: 12,
    padding: 16,
    backgroundColor: '#f0f9ff',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#bae6fd',
  },
  predictionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 12,
    flexWrap: 'wrap',
  },
  predictionTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: '#0284c7',
    flex: 1,
  },
  confidenceBadge: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
  },
  confidenceText: {
    fontSize: 11,
    fontWeight: '600',
  },
  predictionDetails: {
    gap: 8,
  },
  predictionRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  predictionLabel: {
    fontSize: 13,
    color: '#64748b',
  },
  predictionValue: {
    fontSize: 13,
    fontWeight: '500',
    color: '#0f172a',
  },
  adjustmentText: {
    color: '#10b981',
  },
  estimatedRow: {
    paddingTop: 8,
    marginTop: 8,
    borderTopWidth: 1,
    borderTopColor: '#bae6fd',
  },
  estimatedLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: '#0284c7',
  },
  estimatedValue: {
    fontSize: 16,
    fontWeight: '700',
    color: '#0284c7',
  },
  historicalInfo: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 6,
    marginTop: 8,
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: '#bae6fd',
  },
  historicalText: {
    fontSize: 11,
    color: '#64748b',
    flex: 1,
    lineHeight: 16,
  },
  productionRateCard: {
    marginTop: 14,
    backgroundColor: '#f0fdf4',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#bbf7d0',
    overflow: 'hidden',
  },
  productionRateHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 14,
    paddingVertical: 12,
    backgroundColor: '#dcfce7',
    borderBottomWidth: 1,
    borderBottomColor: '#bbf7d0',
  },
  productionRateHeaderLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  productionRateTitle: {
    fontSize: 13,
    fontWeight: '700',
    color: '#166534',
  },
  productionRateBody: {
    padding: 14,
    gap: 14,
  },
  productionRateMembersSection: {
    gap: 8,
  },
  productionRateSectionLabel: {
    fontSize: 10,
    fontWeight: '700',
    color: '#64748b',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    marginBottom: 4,
  },
  productionRateMemberRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 6,
  },
  productionRateMemberRowDivider: {
    borderTopWidth: 1,
    borderTopColor: '#e5e7eb',
    paddingTop: 8,
    marginTop: 2,
  },
  productionRateMemberInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  productionRateMemberDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
  },
  productionRateMemberDotActive: {
    backgroundColor: '#10b981',
  },
  productionRateMemberDotInactive: {
    backgroundColor: '#d1d5db',
  },
  productionRateMemberName: {
    fontSize: 14,
    fontWeight: '500',
    color: '#334155',
  },
  productionRateMemberRate: {
    fontSize: 14,
    fontWeight: '600',
    color: '#059669',
  },
  productionRateMemberNoRate: {
    fontSize: 13,
    fontWeight: '500',
    color: '#94a3b8',
    fontStyle: 'italic',
  },
  productionRateCalculation: {
    gap: 8,
  },
  productionRateFormulaBox: {
    backgroundColor: '#fff',
    borderRadius: 10,
    padding: 12,
    borderWidth: 1,
    borderColor: '#e5e7eb',
    gap: 6,
  },
  productionRateFormulaRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  productionRateFormulaLabel: {
    fontSize: 13,
    color: '#64748b',
  },
  productionRateFormulaValue: {
    fontSize: 13,
    fontWeight: '600',
    color: '#334155',
  },
  productionRateFormulaFormula: {
    fontSize: 13,
    fontWeight: '600',
    color: '#1B4D6E',
    fontFamily: Platform.OS === 'ios' ? 'Menlo' : 'monospace',
  },
  productionRateFormulaDivider: {
    height: 1,
    backgroundColor: '#e5e7eb',
    marginVertical: 4,
  },
  productionRateResult: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#1B4D6E',
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  productionRateResultLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  productionRateResultLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: '#fff',
  },
  productionRateResultValue: {
    fontSize: 20,
    fontWeight: '800',
    color: '#fff',
  },
  productionRateWarning: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
    backgroundColor: '#fef3c7',
    borderRadius: 10,
    padding: 10,
  },
  productionRateWarningText: {
    fontSize: 12,
    color: '#92400e',
    flex: 1,
    lineHeight: 16,
  },
  productionRateNoData: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginTop: 12,
    padding: 14,
    backgroundColor: '#f8fafc',
    borderRadius: 10,
  },
  productionRateNoDataText: {
    fontSize: 13,
    color: '#64748b',
    flex: 1,
  },
  layerCard: {
    marginTop: 14,
    backgroundColor: '#f0f9ff',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#bae6fd',
    overflow: 'hidden',
  },
  layerCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 14,
    paddingVertical: 12,
    backgroundColor: '#e0f2fe',
    borderBottomWidth: 1,
    borderBottomColor: '#bae6fd',
  },
  layerCardHeaderLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  layerCardTitle: {
    fontSize: 13,
    fontWeight: '700',
    color: '#1B4D6E',
  },
  layerCardBody: {
    padding: 14,
    gap: 12,
  },
  layerCardResultRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#fff',
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderWidth: 1,
    borderColor: '#bae6fd',
  },
  layerCardResultLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: '#0369a1',
  },
  layerCardResultSource: {
    fontSize: 11,
    color: '#64748b',
    marginTop: 2,
  },
  layerCardResultValue: {
    fontSize: 24,
    fontWeight: '800',
    color: '#1B4D6E',
  },
  layerCardNote: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
    backgroundColor: '#f0f9ff',
    borderRadius: 10,
    padding: 10,
  },
  layerCardNoteText: {
    fontSize: 12,
    color: '#1B4D6E',
    flex: 1,
    lineHeight: 16,
  },
  layerBadgeCustom: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 10,
    backgroundColor: '#1B4D6E',
  },
  layerBadgeProduction: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 10,
    backgroundColor: '#059669',
  },
  layerBadgeDefault: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 10,
    backgroundColor: '#e2e8f0',
  },
  layerBadgeText: {
    fontSize: 10,
    fontWeight: '700',
    color: '#fff',
    letterSpacing: 0.5,
  },
  durationCollapsed: {
    marginTop: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 14,
    paddingVertical: 12,
    backgroundColor: '#f8fafc',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#e2e8f0',
    borderStyle: 'dashed',
  },
  durationCollapsedTitle: {
    fontSize: 13,
    fontWeight: '600',
    color: '#94a3b8',
  },
  durationCollapsedValue: {
    fontSize: 14,
    fontWeight: '700',
    color: '#475569',
  },
  durationCollapsedAction: {
    fontSize: 12,
    fontWeight: '600',
    color: '#0284c7',
  },
  addressPickerOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.4)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  addressPickerModal: {
    backgroundColor: '#fff',
    borderRadius: 20,
    width: '100%',
    maxWidth: 400,
    maxHeight: '70%',
    overflow: 'hidden',
  },
  addressPickerHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#f1f5f9',
  },
  addressPickerTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#0f172a',
  },
  addressPickerSubtitle: {
    fontSize: 14,
    color: '#64748b',
    paddingHorizontal: 20,
    paddingTop: 12,
    paddingBottom: 8,
  },
  addressPickerList: {
    paddingHorizontal: 12,
    paddingBottom: 16,
  },
  addressPickerItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 14,
    paddingHorizontal: 12,
    marginVertical: 4,
    borderRadius: 12,
    backgroundColor: '#f8fafc',
    borderWidth: 1,
    borderColor: '#e2e8f0',
  },
  addressPickerItemContent: {
    flex: 1,
    gap: 4,
  },
  addressPickerLabelRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  addressPickerLabel: {
    fontSize: 15,
    fontWeight: '600',
    color: '#0f172a',
  },
  addressPickerPrimaryBadge: {
    backgroundColor: '#f0f9ff',
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 8,
  },
  addressPickerPrimaryText: {
    fontSize: 11,
    fontWeight: '600',
    color: '#0284c7',
  },
  addressPickerAddress: {
    fontSize: 13,
    color: '#64748b',
    marginLeft: 24,
    lineHeight: 18,
  },
  countBadge: {
    backgroundColor: '#1B4D6E',
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 10,
  },
  countBadgeText: {
    fontSize: 11,
    fontWeight: '600',
    color: '#fff',
  },
  teamMemberPickerContainer: {
    backgroundColor: '#f8fafc',
    borderRadius: 10,
    marginTop: 6,
    borderWidth: 1,
    borderColor: '#e2e8f0',
    overflow: 'hidden',
  },
  teamMemberPickerList: {
    maxHeight: 180,
  },
  teamMemberCheckboxRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 14,
    paddingVertical: 10,
    gap: 10,
  },
  teamMemberRowDivider: {
    borderTopWidth: 1,
    borderTopColor: '#f1f5f9',
  },
  teamMemberName: {
    fontSize: 14,
    color: '#334155',
    flex: 1,
  },
  teamMemberNameDim: {
    color: '#94a3b8',
  },
  rateBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
    paddingHorizontal: 8,
    paddingVertical: 3,
    backgroundColor: '#dcfce7',
    borderRadius: 20,
  },
  rateBadgeText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#059669',
  },
  missingRatePill: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    backgroundColor: '#fef3c7',
    borderRadius: 20,
  },
  missingRateText: {
    fontSize: 11,
    fontWeight: '600',
    color: '#d97706',
  },
  inlineRateInputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: '#fffbeb',
    borderTopWidth: 1,
    borderTopColor: '#fef3c7',
    gap: 10,
  },
  inlineRateLeft: {
    flex: 1,
    gap: 4,
  },
  inlineRateLabel: {
    fontSize: 10,
    fontWeight: '600',
    color: '#92400e',
    textTransform: 'uppercase',
    letterSpacing: 0.3,
  },
  inlineRateInputWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  inlineRateInput: {
    borderWidth: 1.5,
    borderColor: '#fbbf24',
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 8,
    fontSize: 15,
    fontWeight: '600',
    color: '#0f172a',
    backgroundColor: '#fff',
    minWidth: 80,
  },
  inlineRateRight: {
    alignItems: 'flex-end',
    gap: 6,
  },
  inlinePersistToggle: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  inlinePersistTextOn: {
    fontSize: 11,
    fontWeight: '600',
    color: '#0284c7',
  },
  inlinePersistTextOff: {
    fontSize: 11,
    fontWeight: '500',
    color: '#94a3b8',
  },
  inlineRateSaveBtn: {
    borderRadius: 10,
    overflow: 'hidden' as const,
    minWidth: 64,
  },
  inlineRateSaveBtnGradient: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  inlineRateSaveBtnDisabled: {
    opacity: 0.5,
  },
  inlineRateSaveBtnText: {
    fontSize: 13,
    fontWeight: '700',
    color: '#fff',
  },
  durationEstimateSection: {
    padding: 14,
    gap: 8,
    borderTopWidth: 1,
    borderTopColor: '#f1f5f9',
  },
  warningBox: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    padding: 10,
    backgroundColor: '#fffbeb',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#fde68a',
  },
  warningText: {
    flex: 1,
    fontSize: 12,
    color: '#d97706',
    lineHeight: 16,
  },
  estimateBox: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    padding: 10,
    backgroundColor: '#f0f9ff',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#bae6fd',
  },
  estimateText: {
    flex: 1,
    fontSize: 13,
    fontWeight: '600',
    color: '#0284c7',
  },
  estimateConfidence: {
    fontSize: 11,
    color: '#64748b',
  },
  autoFilledBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 8,
    paddingVertical: 3,
    backgroundColor: '#dcfce7',
    borderRadius: 12,
  },
  autoFilledText: {
    fontSize: 11,
    fontWeight: '600',
    color: '#16a34a',
  },
  inputAutoFilled: {
    borderColor: '#22c55e',
    borderWidth: 1.5,
    backgroundColor: '#f0fdf4',
  },
  paneFilterSection: {
    marginBottom: 12,
    backgroundColor: '#f8fafc',
    borderRadius: 12,
    padding: 14,
    borderWidth: 1,
    borderColor: '#e2e8f0',
  },
  paneFilterTitle: {
    fontSize: 11,
    fontWeight: '600',
    color: '#64748b',
    marginBottom: 8,
    textTransform: 'uppercase',
    letterSpacing: 0.4,
  },
  paneFilterGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
  },
  paneFilterChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#e2e8f0',
    backgroundColor: '#fff',
  },
  paneFilterChipActive: {
    borderColor: '#1B4D6E',
    backgroundColor: '#f0f7ff',
  },
  paneFilterChipLabel: {
    fontSize: 12,
    color: '#64748b',
    fontWeight: '500',
  },
  paneFilterChipLabelActive: {
    color: '#1B4D6E',
  },
  paneFilterChipCount: {
    fontSize: 11,
    fontWeight: '700',
    color: '#94a3b8',
    backgroundColor: '#f1f5f9',
    borderRadius: 8,
    paddingHorizontal: 5,
    paddingVertical: 1,
    minWidth: 20,
    textAlign: 'center',
  },
  paneFilterChipCountActive: {
    color: '#1B4D6E',
    backgroundColor: '#e0f2fe',
  },
  paneChecklistSection: {
    marginBottom: 16,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#e2e8f0',
    overflow: 'hidden',
  },
  paneChecklistHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: '#f0f7ff',
    borderBottomWidth: 1,
    borderBottomColor: '#e2e8f0',
  },
  paneChecklistTitle: {
    fontSize: 11,
    fontWeight: '700',
    color: '#1B4D6E',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  paneChecklistToggleAll: {
    fontSize: 12,
    fontWeight: '600',
    color: '#0284c7',
  },
  paneChecklistTable: {
    backgroundColor: '#fff',
  },
  paneChecklistTableHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 8,
    backgroundColor: '#f8fafc',
    borderBottomWidth: 1,
    borderBottomColor: '#f1f5f9',
    gap: 6,
  },
  paneChecklistColHead: {
    fontSize: 10,
    fontWeight: '700',
    color: '#94a3b8',
    textTransform: 'uppercase',
    letterSpacing: 0.4,
  },
  paneChecklistRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 14,
    backgroundColor: '#fff',
    gap: 6,
  },
  paneChecklistRowDivider: {
    borderTopWidth: 1,
    borderTopColor: '#f1f5f9',
  },
  paneChecklistRowActive: {
    backgroundColor: '#fafcff',
  },
  paneChecklistCheckbox: {
    width: 22,
    height: 22,
    borderRadius: 6,
    borderWidth: 2,
    borderColor: '#cbd5e1',
    backgroundColor: '#f9fafb',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 4,
  },
  paneChecklistCheckboxActive: {
    borderColor: '#1B4D6E',
    backgroundColor: '#1B4D6E',
  },
  paneChecklistTypeLabel: {
    fontSize: 13,
    fontWeight: '600',
    color: '#0f172a',
  },
  paneChecklistTypeLabelDim: {
    color: '#94a3b8',
  },
  paneChecklistCell: {
    fontSize: 13,
    color: '#334155',
    fontWeight: '500',
  },
  paneChecklistSubtotal: {
    fontWeight: '700',
    textAlign: 'right',
  },
  paneChecklistCellDim: {
    color: '#cbd5e1',
  },
  paneChecklistTotalRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: '#f0f7ff',
    borderTopWidth: 2,
    borderTopColor: '#bae6fd',
  },
  paneChecklistTotalLabel: {
    fontSize: 12,
    fontWeight: '600',
    color: '#475569',
  },
  paneChecklistTotalValue: {
    fontSize: 18,
    fontWeight: '800',
    color: '#1B4D6E',
  },
  paneCountInput: {
    width: 60,
    height: 36,
    borderWidth: 1.5,
    borderColor: '#bae6fd',
    borderRadius: 8,
    backgroundColor: '#f0f9ff',
    textAlign: 'center',
    fontSize: 14,
    fontWeight: '700',
    color: '#1B4D6E',
    paddingHorizontal: 4,
  },
  addPaneTypeRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderTopWidth: 1,
    borderTopColor: '#f1f5f9',
    backgroundColor: '#fafcff',
  },
  addPaneTypeChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
    borderWidth: 1.5,
    borderColor: '#bae6fd',
    backgroundColor: '#f0f9ff',
  },
  addPaneTypeChipLabel: {
    fontSize: 12,
    fontWeight: '600',
    color: '#0284c7',
  },
  propQualInfoSection: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#e2e8f0',
    overflow: 'hidden',
  },
  propQualInfoTitle: {
    fontSize: 11,
    fontWeight: '700',
    color: '#94a3b8',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    paddingHorizontal: 16,
    paddingVertical: 10,
    backgroundColor: '#f8fafc',
    borderBottomWidth: 1,
    borderBottomColor: '#f1f5f9',
  },
  propQualInfoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderTopWidth: 1,
    borderTopColor: '#f1f5f9',
  },
  propQualInfoLabel: {
    fontSize: 13,
    fontWeight: '600',
    color: '#334155',
    flex: 1,
  },
  propQualInfoValue: {
    fontSize: 13,
    fontWeight: '600',
    color: '#1B4D6E',
  },
  createChecklistContainer: {
    backgroundColor: '#f8fafc',
    borderRadius: 10,
    padding: 12,
    marginTop: 6,
    borderWidth: 1,
    borderColor: '#e2e8f0',
  },
  createChecklistHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  createChecklistTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: '#0f172a',
  },
  createChecklistInput: {
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#e2e8f0',
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 15,
    color: '#0f172a',
    marginBottom: 12,
  },
  checklistItemsSection: {
    marginBottom: 12,
  },
  checklistItemsLabel: {
    fontSize: 11,
    fontWeight: '600',
    color: '#64748b',
    textTransform: 'uppercase',
    letterSpacing: 0.3,
    marginBottom: 8,
  },
  checklistItemRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#fff',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    marginBottom: 6,
    borderWidth: 1,
    borderColor: '#f1f5f9',
  },
  checklistItemText: {
    fontSize: 14,
    color: '#334155',
    flex: 1,
  },
  addChecklistItemRow: {
    flexDirection: 'row',
    gap: 8,
  },
  addChecklistItemInput: {
    flex: 1,
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#e2e8f0',
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 14,
    color: '#0f172a',
  },
  addChecklistItemButton: {
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#e2e8f0',
    borderRadius: 10,
    width: 42,
    height: 42,
    justifyContent: 'center',
    alignItems: 'center',
  },
  createChecklistButton: {
    borderRadius: 10,
    overflow: 'hidden' as const,
  },
  createChecklistButtonGradient: {
    paddingVertical: 12,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 8,
  },
  createChecklistButtonDisabled: {
    opacity: 0.5,
  },
  createChecklistButtonText: {
    color: '#fff',
    fontSize: 15,
    fontWeight: '600',
  },
  serviceScopeSection: {
    marginBottom: 16,
  },
  serviceScopeButtons: {
    flexDirection: 'row',
    gap: 8,
  },
  serviceScopeButton: {
    flex: 1,
    paddingVertical: 11,
    paddingHorizontal: 12,
    borderRadius: 12,
    backgroundColor: '#f8fafc',
    borderWidth: 1,
    borderColor: '#e2e8f0',
    alignItems: 'center',
  },
  serviceScopeButtonActive: {
    backgroundColor: '#1B4D6E',
    borderColor: '#1B4D6E',
  },
  serviceScopeButtonText: {
    fontSize: 13,
    fontWeight: '500',
    color: '#64748b',
  },
  serviceScopeButtonTextActive: {
    color: '#fff',
  },
  lineItemsSection: {
    marginBottom: 16,
    paddingTop: 14,
    borderTopWidth: 1,
    borderTopColor: '#f1f5f9',
  },
  lineItemsHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 12,
  },
  lineItemsHeaderText: {
    fontSize: 11,
    fontWeight: '600',
    color: '#64748b',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  lineItemCard: {
    backgroundColor: '#f8fafc',
    borderRadius: 10,
    padding: 12,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: '#e2e8f0',
  },
  lineItemHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  lineItemNumber: {
    fontSize: 11,
    fontWeight: '700',
    color: '#64748b',
    textTransform: 'uppercase',
  },
  lineItemRemoveBtn: {
    padding: 4,
  },
  lineItemDetails: {
    marginTop: 10,
  },
  lineItemScopeRow: {
    flexDirection: 'row',
    gap: 6,
    marginBottom: 10,
  },
  lineItemScopeBtn: {
    flex: 1,
    paddingVertical: 7,
    paddingHorizontal: 8,
    borderRadius: 8,
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#e2e8f0',
    alignItems: 'center',
  },
  lineItemScopeBtnActive: {
    backgroundColor: '#1B4D6E',
    borderColor: '#1B4D6E',
  },
  lineItemScopeBtnText: {
    fontSize: 11,
    fontWeight: '500',
    color: '#64748b',
  },
  lineItemScopeBtnTextActive: {
    color: '#fff',
  },
  lineItemQtyRow: {
    flexDirection: 'row',
    gap: 10,
  },
  lineItemQtyField: {
    flex: 1,
  },
  lineItemTotalField: {
    flex: 1,
    alignItems: 'flex-end',
  },
  lineItemFieldLabel: {
    fontSize: 10,
    fontWeight: '600',
    color: '#64748b',
    marginBottom: 4,
    textTransform: 'uppercase',
    letterSpacing: 0.3,
  },
  lineItemInput: {
    backgroundColor: '#fff',
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 9,
    fontSize: 14,
    color: '#0f172a',
    borderWidth: 1,
    borderColor: '#e2e8f0',
  },
  lineItemTotalValue: {
    fontSize: 16,
    fontWeight: '700',
    color: '#0f172a',
    paddingTop: 8,
  },
  addServiceButtonRow: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    marginBottom: 16,
  },
  addServiceButton: {
    borderRadius: 10,
    overflow: 'hidden' as const,
  },
  addServiceButtonGradient: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
    paddingVertical: 10,
    paddingHorizontal: 14,
  },
  addServiceButtonText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#fff',
  },
});
