import { Platform, StyleSheet, Dimensions } from 'react-native';
import { SPACING, TYPOGRAPHY, CARD, ICON, SEARCH_BAR, FAB, HEADER, ICON_BUTTON, COLORS, CARD_SHADOW } from '@/constants/designSystem';

const getDynamicStyles = (colors: any) =>
  StyleSheet.create({
    container: {
      flex: 1,
      width: '100%',
      maxWidth: '100%',
      backgroundColor: colors.background,
      alignSelf: 'stretch',
    },
    header: {
      backgroundColor: colors.surface,
      paddingTop: 12,
      paddingHorizontal: 16,
      paddingBottom: 12,
      width: '100%',
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: colors.border,
    },
    headerTop: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    headerLeft: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: SPACING.md,
    },
    headerTitle: {
      fontSize: 18,
      fontWeight: '700',
      color: '#1B4D6E',
      position: 'absolute',
      left: 0,
      right: 0,
      textAlign: 'center',
    },
    todayButton: {
      width: 36,
      height: 36,
      backgroundColor: colors.primary,
      borderRadius: 8,
      alignItems: 'center',
      justifyContent: 'center',
    },
    todayButtonText: {
      color: '#fff',
      fontSize: 14,
      fontWeight: '700',
    },
    viewSwitcher: {
      flexDirection: 'row',
      backgroundColor: colors.inputBackground,
      borderRadius: 8,
      padding: 2,
      gap: 2,
    },
    viewButton: {
      paddingHorizontal: SPACING.md,
      paddingVertical: SPACING.xs + 2,
      borderRadius: 6,
    },
    activeViewButton: {
      backgroundColor: colors.primary,
    },
    viewButtonText: {
      fontSize: 12,
      fontWeight: '600',
      color: colors.textSecondary,
    },
    activeViewButtonText: {
      color: '#fff',
    },
    iconButton: {
      width: 36,
      height: 36,
      backgroundColor: colors.inputBackground,
      borderRadius: 18,
      alignItems: 'center',
      justifyContent: 'center',
    },
    tabContainer: {
      flexDirection: 'row',
      backgroundColor: colors.inputBackground,
      borderRadius: 8,
      padding: 3,
      marginTop: SPACING.md,
      marginBottom: SPACING.md,
      marginHorizontal: 16,
    },
    tab: {
      flex: 1,
      paddingVertical: SPACING.sm,
      paddingHorizontal: SPACING.md,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: 6,
    },
    activeTab: {
      backgroundColor: colors.primary,
    },
    tabText: {
      fontSize: 13,
      fontWeight: '600',
      color: colors.textSecondary,
      textAlign: 'center',
    },
    activeTabText: {
      color: '#fff',
    },
    monthNavigation: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      width: '100%',
      paddingHorizontal: 16,
      marginBottom: SPACING.md,
      flexWrap: 'wrap',
      gap: SPACING.sm,
    },
    navButton: {
      padding: SPACING.sm,
    },
    monthText: {
      fontSize: Platform.OS === 'web' ? 18 : 16,
      fontWeight: '700',
      color: colors.text,
      flexShrink: 1,
    },
    searchContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.inputBackground,
      borderRadius: 8,
      paddingHorizontal: 12,
      paddingVertical: 8,
      marginHorizontal: 16,
      marginTop: SPACING.md,
      marginBottom: SPACING.sm,
      gap: SPACING.sm,
    },
    searchInput: {
      flex: 1,
      fontSize: 14,
      color: colors.text,
      padding: 0,
      margin: 0,
      borderWidth: 0,
      backgroundColor: 'transparent',
      ...(Platform.OS === 'web' ? { outlineStyle: 'none' } : {}),
    } as any,
    scrollView: {
      flex: 1,
      width: '100%',
    },
    scrollViewContent: {
      flexGrow: 1,
      width: '100%',
      paddingBottom: 80,
    },
    calendar: {
      backgroundColor: colors.surface,
      padding: SPACING.lg,
      width: '100%',
    },
    weekDays: {
      flexDirection: 'row',
      width: '100%',
      marginBottom: SPACING.xs,
      alignItems: 'stretch',
    },
    weekDay: {
      flex: 1,
      alignItems: 'center',
      paddingVertical: SPACING.xs + 2,
    },
    weekDayText: {
      fontSize: 11,
      fontWeight: '700',
      color: colors.textSecondary,
      textTransform: 'uppercase',
      letterSpacing: 0.5,
    },
    daysGrid: {
      flexDirection: 'column',
      width: '100%',
      alignItems: 'stretch',
    },
    dayViewContainer: {
      width: '100%',
      padding: SPACING.lg,
    },
    dayViewContent: {
      width: '100%',
      gap: SPACING.md,
    },
    emptyDayView: {
      padding: SPACING.xxl + SPACING.sm,
      alignItems: 'center',
      justifyContent: 'center',
    },
    emptyDayText: {
      fontSize: 15,
      color: colors.textSecondary,
      textAlign: 'center',
    },
    weekRow: {
      flexDirection: 'row',
      width: '100%',
    },
    dayCell: {
      flex: 1,
      minHeight: Platform.OS === 'web' ? 100 : 88,
      padding: SPACING.xs,
      alignItems: 'flex-start',
      justifyContent: 'flex-start',
    },
    emptyCel: {
      backgroundColor: colors.background,
    },
    todayCell: {
      backgroundColor: colors.primaryLight,
    },
    selectedCell: {
      backgroundColor: colors.primary + '0C',
      borderColor: colors.primary + '30',
    },
    dropZone: {
      borderWidth: 2,
      borderStyle: 'dashed',
      borderColor: colors.primary,
      opacity: 0.6,
    },
    dropZoneActive: {
      backgroundColor: colors.primaryLight,
      borderColor: colors.primary,
      borderStyle: 'solid',
      borderWidth: 3,
      opacity: 1,
      transform: [{ scale: 1.05 }],
    },
    dayNumber: {
      width: 26,
      height: 26,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: 13,
      marginBottom: 2,
    },
    todayNumber: {
      backgroundColor: colors.primary,
    },
    selectedNumber: {
      backgroundColor: colors.primary + '20',
    },
    dayText: {
      fontSize: 13,
      color: colors.text,
      fontWeight: '500',
    },
    todayText: {
      color: '#fff',
      fontWeight: '700',
    },
    selectedText: {
      color: colors.primary,
      fontWeight: '700',
    },
    eventDots: {
      flexDirection: 'row',
      gap: 2,
      marginTop: 2,
    },
    eventDot: {
      width: 4,
      height: 4,
      borderRadius: 2,
      backgroundColor: colors.primary,
    },
    moreEventsText: {
      fontSize: 8,
      color: colors.primary,
      marginTop: 2,
    },
    upcomingSection: {
      padding: SPACING.lg,
    },
    sectionHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: SPACING.md,
    },
    upcomingTitle: {
      fontSize: 12,
      fontWeight: '700',
      color: colors.textSecondary,
      textTransform: 'uppercase',
      letterSpacing: 1,
    },
    clearButton: {
      fontSize: 12,
      color: colors.primary,
      fontWeight: '600',
    },
    eventCard: {
      backgroundColor: colors.cardBackground,
      borderRadius: CARD.borderRadius,
      marginBottom: SPACING.sm,
      flexDirection: 'row',
      overflow: 'hidden',
      ...CARD_SHADOW,
      borderWidth: CARD.borderWidth,
      borderColor: colors.border,
    },
    eventCardStripe: {
      width: 4,
      borderRadius: 0,
    },
    eventCardBody: {
      flex: 1,
      padding: SPACING.md,
    },
    eventCardHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 4,
    },
    titleRow: {
      flexDirection: 'row',
      alignItems: 'center',
      flex: 1,
      gap: SPACING.sm,
    },
    recurringBadge: {
      width: 18,
      height: 18,
      borderRadius: 9,
      backgroundColor: colors.primaryLight,
      alignItems: 'center',
      justifyContent: 'center',
    },
    eventTitle: {
      fontSize: 14,
      fontWeight: '700',
      color: colors.text,
      flex: 1,
    },
    eventStatusBadge: {
      paddingHorizontal: 7,
      paddingVertical: 2,
      borderRadius: 10,
    },
    eventStatusText: {
      fontSize: 9,
      fontWeight: '700',
      textTransform: 'uppercase',
      letterSpacing: 0.5,
    },
    recurrenceText: {
      fontSize: 11,
      color: colors.primary,
      fontWeight: '500',
      marginTop: 2,
      marginBottom: 2,
    },
    timeContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: SPACING.xs,
    },
    timeText: {
      fontSize: 11,
      color: colors.textSecondary,
      fontWeight: '600',
    },
    eventDate: {
      fontSize: 12,
      color: colors.textSecondary,
      marginBottom: 2,
    },
    clientName: {
      fontSize: 12,
      color: colors.textSecondary,
      marginTop: 2,
    },
    eventDescription: {
      fontSize: 12,
      color: colors.textSecondary,
      marginTop: SPACING.xs,
      marginBottom: 2,
    },
    eventLocation: {
      fontSize: 11,
      color: colors.textSecondary,
      marginTop: 2,
    },
    eventLocationClickable: {
      marginTop: SPACING.xs,
    },
    fab: {
      position: 'absolute',
      right: SPACING.xl,
      bottom: SPACING.xl,
      width: FAB.size,
      height: FAB.size,
      borderRadius: FAB.borderRadius,
      backgroundColor: colors.primary,
      justifyContent: 'center',
      alignItems: 'center',
      ...(FAB as any),
    },
    emptyContainer: {
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: SPACING.xxl + SPACING.sm,
    },
    emptyText: {
      fontSize: 15,
      fontWeight: '600',
      color: colors.textSecondary,
      marginBottom: SPACING.sm,
    },
    emptySubtext: {
      fontSize: 13,
      color: colors.textSecondary,
      textAlign: 'center',
    },
    paymentRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginTop: SPACING.md,
      paddingTop: SPACING.md,
      borderTopWidth: StyleSheet.hairlineWidth,
      borderTopColor: colors.border,
    },
    amountText: {
      fontSize: 15,
      fontWeight: '700',
      color: colors.text,
    },
    paidBadge: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: SPACING.xs,
      backgroundColor: '#3dba6f',
      paddingHorizontal: SPACING.md,
      paddingVertical: SPACING.xs + 2,
      borderRadius: SPACING.lg,
    },
    paidBadgeText: {
      fontSize: 11,
      fontWeight: '700',
      color: '#fff',
    },
    markPaidButton: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: SPACING.xs,
      backgroundColor: colors.successBackground,
      paddingHorizontal: SPACING.md,
      paddingVertical: SPACING.xs + 2,
      borderRadius: SPACING.lg,
      borderWidth: 1,
      borderColor: '#3dba6f',
    },
    markPaidButtonText: {
      fontSize: 11,
      fontWeight: '700',
      color: '#3dba6f',
    },
    paymentModalOverlay: {
      flex: 1,
      backgroundColor: 'rgba(0,0,0,0.5)',
      justifyContent: 'center',
      alignItems: 'center',
      padding: SPACING.xl,
    },
    paymentModalContent: {
      backgroundColor: colors.cardBackground,
      borderRadius: 12,
      padding: SPACING.xl,
      width: '100%',
      maxWidth: 320,
    },
    paymentModalTitle: {
      fontSize: 16,
      fontWeight: '700',
      color: colors.text,
      textAlign: 'center',
      marginBottom: SPACING.lg,
    },
    amountInputContainer: {
      marginBottom: SPACING.xl,
    },
    amountInputLabel: {
      fontSize: 13,
      fontWeight: '600',
      color: colors.textSecondary,
      marginBottom: SPACING.sm,
    },
    amountInputRow: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.inputBackground,
      borderRadius: 8,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.border,
      paddingHorizontal: SPACING.md,
    },
    currencySymbol: {
      fontSize: 16,
      fontWeight: '700',
      color: colors.text,
      marginRight: SPACING.xs,
    },
    amountInput: {
      flex: 1,
      fontSize: 16,
      fontWeight: '700',
      color: colors.text,
      paddingVertical: SPACING.md,
    },
    paymentMethodLabel: {
      fontSize: 13,
      fontWeight: '600',
      color: colors.textSecondary,
      marginBottom: SPACING.sm,
    },
    paymentMethodList: {
      gap: SPACING.sm,
    },
    paymentMethodOption: {
      paddingVertical: SPACING.md + 2,
      paddingHorizontal: SPACING.lg,
      backgroundColor: colors.inputBackground,
      borderRadius: 8,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.border,
    },
    paymentMethodOptionText: {
      fontSize: 14,
      color: colors.text,
      textAlign: 'center',
      fontWeight: '500',
    },
    paymentModalCancel: {
      marginTop: SPACING.lg,
      paddingVertical: SPACING.md + 2,
    },
    paymentModalCancelText: {
      fontSize: 14,
      color: colors.textSecondary,
      textAlign: 'center',
      fontWeight: '500',
    },
    deleteEventButton: {
      padding: SPACING.xs + 2,
      borderRadius: 6,
      backgroundColor: colors.errorBackground || '#fee2e2',
    },
  });

export default getDynamicStyles;
