import { StyleSheet } from 'react-native';

const getDynamicStyles = (colors: any) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.background,
    },
    scrollContent: {
      flexGrow: 1,
      justifyContent: 'center',
      padding: 20,
      paddingBottom: 40,
    },
    logoContainer: {
      alignItems: 'center',
      marginBottom: 24,
    },
    subtitle: {
      fontSize: 16,
      color: colors.textSecondary,
      marginBottom: 24,
      textAlign: 'center',
    },
    form: {
      gap: 14,
    },
    input: {
      backgroundColor: colors.inputBackground,
      borderRadius: 10,
      padding: 16,
      fontSize: 16,
      borderWidth: 1,
      borderColor: colors.border,
      color: colors.text,
    },
    button: {
      borderRadius: 10,
      overflow: 'hidden' as const,
      marginTop: 8,
    },
    buttonGradient: {
      padding: 16,
      alignItems: 'center' as const,
    },
    buttonDisabled: {
      opacity: 0.5,
    },
    buttonText: {
      color: '#fff',
      fontSize: 16,
      fontWeight: '600',
    },
    linkText: {
      color: colors.primary,
      fontSize: 14,
      textAlign: 'center',
      marginTop: 8,
    },
    errorContainer: {
      backgroundColor: colors.errorBackground,
      borderRadius: 10,
      padding: 12,
      marginBottom: 16,
    },
    errorText: {
      color: colors.error,
      fontSize: 14,
      textAlign: 'center',
    },
    roleSectionHeader: {
      marginTop: 8,
      marginBottom: 4,
    },
    roleSectionTitle: {
      fontSize: 16,
      fontWeight: '600',
      color: colors.text,
    },
    roleCards: {
      flexDirection: 'row',
      gap: 12,
    },
    roleCard: {
      flex: 1,
      backgroundColor: colors.surface,
      borderRadius: 14,
      padding: 16,
      borderWidth: 2,
      borderColor: colors.border,
      overflow: 'hidden',
    },
    roleCardSelected: {
      borderColor: colors.primary,
      backgroundColor: colors.primary + '08',
    },
    roleCardHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'flex-start',
      marginBottom: 12,
    },
    roleIcon: {
      width: 42,
      height: 42,
      borderRadius: 12,
      alignItems: 'center',
      justifyContent: 'center',
    },
    infoButton: {
      width: 28,
      height: 28,
      borderRadius: 14,
      backgroundColor: colors.inputBackground,
      alignItems: 'center',
      justifyContent: 'center',
    },
    roleCardTitle: {
      fontSize: 15,
      fontWeight: '700',
      color: colors.text,
      marginBottom: 4,
    },
    roleCardDesc: {
      fontSize: 13,
      color: colors.textSecondary,
      lineHeight: 18,
    },
    roleSelectedIndicator: {
      position: 'absolute',
      bottom: 0,
      left: 0,
      right: 0,
      height: 3,
      borderBottomLeftRadius: 14,
      borderBottomRightRadius: 14,
    },
    roleDetailSection: {
      gap: 8,
    },
    roleDetailLabel: {
      fontSize: 15,
      fontWeight: '600',
      color: colors.text,
    },
    roleDetailHint: {
      fontSize: 13,
      color: colors.textSecondary,
      marginBottom: 4,
    },
    codeInputRow: {
      flexDirection: 'row',
      gap: 8,
      justifyContent: 'center',
    },
    codeInput: {
      width: 46,
      height: 54,
      borderRadius: 10,
      borderWidth: 2,
      borderColor: colors.border,
      backgroundColor: colors.inputBackground,
      textAlign: 'center',
      fontSize: 22,
      fontWeight: '700',
      color: colors.text,
    },
    codeInputFilled: {
      borderColor: colors.primary,
      backgroundColor: colors.primary + '08',
    },
    modalOverlay: {
      flex: 1,
      backgroundColor: 'rgba(0, 0, 0, 0.5)',
      justifyContent: 'center',
      alignItems: 'center',
      padding: 20,
    },
    infoModalContent: {
      backgroundColor: colors.surface,
      borderRadius: 20,
      padding: 28,
      width: '100%',
      maxWidth: 360,
      alignItems: 'center',
    },
    infoModalIcon: {
      width: 56,
      height: 56,
      borderRadius: 16,
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 16,
    },
    infoModalTitle: {
      fontSize: 20,
      fontWeight: '700',
      color: colors.text,
      marginBottom: 12,
      textAlign: 'center',
    },
    infoModalText: {
      fontSize: 15,
      color: colors.textSecondary,
      textAlign: 'center',
      marginBottom: 12,
      lineHeight: 22,
    },
    successModalContent: {
      backgroundColor: colors.surface,
      borderRadius: 20,
      padding: 28,
      width: '100%',
      maxWidth: 380,
      alignItems: 'center',
    },
    successIcon: {
      width: 72,
      height: 72,
      borderRadius: 36,
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 16,
    },
    successTitle: {
      fontSize: 22,
      fontWeight: '700',
      color: colors.text,
      marginBottom: 4,
    },
    successOrgName: {
      fontSize: 16,
      fontWeight: '600',
      color: colors.primary,
      marginBottom: 16,
    },
    successText: {
      fontSize: 15,
      color: colors.textSecondary,
      textAlign: 'center',
      marginBottom: 16,
      lineHeight: 22,
    },
    codeDisplayContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.inputBackground,
      borderRadius: 14,
      paddingVertical: 16,
      paddingHorizontal: 24,
      gap: 16,
      borderWidth: 2,
      borderColor: colors.primary + '30',
      borderStyle: 'dashed',
    },
    codeDisplayText: {
      fontSize: 32,
      fontWeight: '800',
      color: colors.text,
      letterSpacing: 6,
    },
    copyButton: {
      width: 36,
      height: 36,
      borderRadius: 10,
      backgroundColor: colors.primary + '15',
      alignItems: 'center',
      justifyContent: 'center',
    },
    copiedText: {
      fontSize: 13,
      fontWeight: '600',
      color: '#16a34a',
      marginTop: 8,
    },
    successHint: {
      fontSize: 13,
      color: colors.textSecondary,
      textAlign: 'center',
      marginTop: 12,
    },
    buttonSecondary: {
      backgroundColor: colors.surface,
      borderWidth: 2,
      borderColor: colors.primary,
    },
    termsContainer: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      paddingVertical: 16,
      paddingHorizontal: 4,
      gap: 12,
    },
    checkboxContainer: {
      paddingTop: 2,
    },
    termsTextContainer: {
      flex: 1,
    },
    termsText: {
      fontSize: 14,
      color: colors.textSecondary,
      lineHeight: 20,
    },
    termsLink: {
      color: colors.primary,
      fontWeight: '600',
      textDecorationLine: 'underline',
    },
  });

export default getDynamicStyles;
