import { Platform, StyleSheet } from 'react-native';
import { SPACING, TYPOGRAPHY, CARD, ICON, SEARCH_BAR, FAB, HEADER, ICON_BUTTON, COLORS, getElevation } from '@/constants/designSystem';

const getButtonShadow = (isDark: boolean) => Platform.select({
  web: {
    boxShadow: isDark
      ? '0 4px 14px rgba(0,0,0,0.4)'
      : '0 4px 14px rgba(0,0,0,0.18)',
  },
  default: {
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: isDark ? 0.4 : 0.18,
    shadowRadius: 8,
    elevation: 6,
  },
}) as any;

const getDynamicStyles = (colors: any, isDark: boolean) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.background,
    },
    header: {
      paddingHorizontal: HEADER.paddingHorizontal,
      paddingTop: HEADER.paddingVertical,
      paddingBottom: HEADER.paddingVertical,
      backgroundColor: colors.surface,
    },
    headerTopRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      width: '100%',
    },
    title: {
      fontSize: TYPOGRAPHY.screenTitle.fontSize,
      fontWeight: TYPOGRAPHY.screenTitle.fontWeight,
      color: COLORS.brand,
      position: 'absolute',
      left: 0,
      right: 0,
      textAlign: 'center',
    },
    headerActions: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: SPACING.md,
    },
    historyButton: {
      width: ICON_BUTTON.size,
      height: ICON_BUTTON.size,
      borderRadius: ICON_BUTTON.borderRadius,
      backgroundColor: colors.inputBackground,
      borderWidth: ICON_BUTTON.borderWidth,
      borderColor: CARD.borderColor,
      alignItems: 'center',
      justifyContent: 'center',
    },
    teamToggle: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: SPACING.xs + 2,
      paddingVertical: SPACING.sm,
      paddingHorizontal: SPACING.md,
      borderRadius: ICON_BUTTON.borderRadius,
      backgroundColor: colors.inputBackground,
      borderWidth: ICON_BUTTON.borderWidth,
      borderColor: CARD.borderColor,
    },
    teamToggleActive: {
      backgroundColor: colors.primary,
    },
    teamToggleText: {
      fontSize: TYPOGRAPHY.body.fontSize,
      fontWeight: TYPOGRAPHY.heading.fontWeight,
      color: colors.primary,
    },
    teamToggleTextActive: {
      color: '#fff',
    },
    userBadge: {
      backgroundColor: colors.inputBackground,
      paddingHorizontal: SPACING.sm,
      paddingVertical: 3,
      borderRadius: CARD.borderRadius,
    },
    userBadgeOwn: {
      backgroundColor: colors.primaryLight,
    },
    userBadgeText: {
      fontSize: TYPOGRAPHY.caption.fontSize,
      fontWeight: TYPOGRAPHY.bodyMedium.fontWeight,
      color: colors.textSecondary,
    },
    userBadgeTextOwn: {
      color: colors.primary,
    },

    scrollContent: {
      paddingBottom: 120,
    },

    activeStatusBar: {
      backgroundColor: colors.primary,
      paddingHorizontal: SPACING.xl,
      paddingVertical: SPACING.md,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginHorizontal: SPACING.md,
      borderRadius: 16,
      marginBottom: SPACING.xs,
    },
    activeStatusLeft: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: SPACING.md,
      flex: 1,
    },
    activeStatusText: {
      fontSize: TYPOGRAPHY.headingMedium.fontSize,
      fontWeight: TYPOGRAPHY.heading.fontWeight,
      color: '#ffffff',
    },
    activeStatusSubtext: {
      fontSize: TYPOGRAPHY.label.fontSize,
      color: 'rgba(255,255,255,0.85)',
      marginTop: 2,
    },
    activeTimerLarge: {
      fontSize: 22,
      fontWeight: '800',
      color: '#ffffff',
      letterSpacing: 1,
    },

    detectedLocationBanner: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.primary + '18',
      borderWidth: 1,
      borderColor: colors.primary + '40',
      borderRadius: CARD.borderRadius,
      marginHorizontal: SPACING.lg,
      marginTop: SPACING.md,
      marginBottom: 0,
      paddingHorizontal: SPACING.lg,
      paddingVertical: SPACING.md,
      gap: SPACING.sm,
    },
    detectedLocationBannerText: {
      fontSize: TYPOGRAPHY.body.fontSize,
      fontWeight: TYPOGRAPHY.heading.fontWeight,
      color: colors.primary,
      flex: 1,
    },

    viewModeToggle: {
      flexDirection: 'row',
      padding: SPACING.xs,
      backgroundColor: colors.inputBackground,
      borderRadius: SPACING.sm,
      marginHorizontal: SPACING.lg,
      marginBottom: SPACING.md,
      marginTop: SPACING.lg,
    },
    filterContainer: {
      paddingHorizontal: SPACING.lg,
      paddingBottom: SPACING.md,
    },
    viewModeButton: {
      flex: 1,
      paddingVertical: SPACING.sm,
      paddingHorizontal: SPACING.md,
      borderRadius: SPACING.xs + 2,
      alignItems: 'center',
    },
    viewModeButtonActive: {
      backgroundColor: colors.primary,
    },
    viewModeButtonText: {
      fontSize: TYPOGRAPHY.body.fontSize,
      color: colors.textSecondary,
      fontWeight: TYPOGRAPHY.heading.fontWeight,
    },
    viewModeButtonTextActive: {
      color: '#fff',
    },

    entryCard: {
      backgroundColor: colors.cardBackground,
      borderRadius: CARD.borderRadius,
      padding: CARD.padding,
      marginHorizontal: SPACING.lg,
      marginBottom: SPACING.md,
      ...getElevation(1, isDark),
      borderWidth: CARD.borderWidth,
      borderColor: colors.border,
    },
    entryCardTouchable: {
      backgroundColor: colors.cardBackground,
      borderRadius: CARD.borderRadius,
      marginHorizontal: SPACING.lg,
      marginBottom: SPACING.md,
      ...getElevation(1, isDark),
      borderWidth: CARD.borderWidth,
      borderColor: colors.border,
      overflow: 'hidden' as const,
    },
    entryCardInner: {
      padding: CARD.padding,
    },
    entryHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: SPACING.sm,
    },
    entryDate: {
      fontSize: TYPOGRAPHY.headingMedium.fontSize,
      fontWeight: TYPOGRAPHY.headingMedium.fontWeight,
      color: colors.text,
      lineHeight: TYPOGRAPHY.headingMedium.lineHeight,
    },
    entryActions: {
      flexDirection: 'row',
      gap: SPACING.md,
    },
    entryTime: {
      fontSize: TYPOGRAPHY.body.fontSize,
      color: COLORS.text.secondary,
      lineHeight: TYPOGRAPHY.body.lineHeight,
      marginBottom: SPACING.xs,
    },
    entryDuration: {
      fontSize: TYPOGRAPHY.heading.fontSize,
      fontWeight: '700',
      color: colors.primary,
      marginTop: SPACING.sm,
    },
    activeTag: {
      backgroundColor: colors.primary,
      paddingHorizontal: SPACING.sm,
      paddingVertical: SPACING.xs,
      borderRadius: SPACING.xs,
      marginLeft: SPACING.sm,
    },
    activeTagText: {
      color: '#fff',
      fontSize: TYPOGRAPHY.caption.fontSize,
      fontWeight: '700',
    },
    entryCompactRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: SPACING.sm,
    },
    entryTimeCompact: {
      fontSize: 15,
      fontWeight: TYPOGRAPHY.heading.fontWeight,
      color: colors.text,
    },
    entryDurationCompact: {
      fontSize: 15,
      fontWeight: '700',
      color: colors.primary,
    },

    entryFooterRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginTop: SPACING.sm,
      paddingTop: SPACING.sm,
      borderTopWidth: 1,
      borderTopColor: isDark ? 'rgba(255,255,255,0.06)' : 'rgba(0,0,0,0.05)',
    },
    entryFooterBadges: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: SPACING.xs + 2,
      flex: 1,
    },
    entryTapHint: {
      fontSize: 11,
      color: colors.textSecondary,
      opacity: 0.6,
    },

    notesContainer: {
      marginTop: SPACING.md,
      padding: SPACING.md,
      backgroundColor: colors.inputBackground,
      borderRadius: SPACING.sm,
    },
    notesLabel: {
      fontSize: TYPOGRAPHY.caption.fontSize,
      color: colors.textSecondary,
      marginBottom: SPACING.xs,
      fontWeight: TYPOGRAPHY.heading.fontWeight,
    },
    notesText: {
      fontSize: TYPOGRAPHY.body.fontSize,
      color: colors.text,
    },
    notesInput: {
      backgroundColor: colors.inputBackground,
      borderRadius: SPACING.sm,
      padding: SPACING.md,
      marginTop: SPACING.md,
      fontSize: TYPOGRAPHY.body.fontSize,
      color: colors.text,
      minHeight: 80,
      textAlignVertical: 'top',
    },
    notesActions: {
      flexDirection: 'row',
      gap: SPACING.sm,
      marginTop: SPACING.sm,
    },
    notesButton: {
      flex: 1,
      paddingVertical: SPACING.sm,
      paddingHorizontal: SPACING.lg,
      borderRadius: SPACING.xs + 2,
      alignItems: 'center',
    },
    notesSaveButton: {
      backgroundColor: colors.primary,
    },
    notesCancelButton: {
      backgroundColor: colors.textSecondary,
    },
    notesButtonText: {
      color: '#fff',
      fontSize: TYPOGRAPHY.body.fontSize,
      fontWeight: TYPOGRAPHY.heading.fontWeight,
    },

    reportCard: {
      backgroundColor: colors.cardBackground,
      borderRadius: CARD.borderRadius,
      padding: CARD.padding,
      marginHorizontal: SPACING.xl,
      marginBottom: SPACING.md,
      ...getElevation(1, isDark),
      borderWidth: CARD.borderWidth,
      borderColor: colors.border,
    },
    reportHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    reportPeriod: {
      fontSize: TYPOGRAPHY.heading.fontSize,
      fontWeight: '700',
      color: colors.text,
    },
    reportStats: {
      flexDirection: 'row',
      gap: SPACING.xl,
      marginTop: SPACING.md,
    },
    reportStat: {
      alignItems: 'center',
    },
    reportStatLabel: {
      fontSize: TYPOGRAPHY.caption.fontSize,
      color: colors.textSecondary,
      marginBottom: SPACING.xs,
    },
    reportStatValue: {
      fontSize: 20,
      fontWeight: '700',
      color: colors.primary,
    },
    reportEntries: {
      marginTop: SPACING.lg,
      paddingTop: SPACING.lg,
      borderTopWidth: 1,
      borderTopColor: colors.border,
    },
    reportEntriesTitle: {
      fontSize: TYPOGRAPHY.body.fontSize,
      fontWeight: '700',
      color: colors.text,
      marginBottom: SPACING.sm,
    },
    reportEntryRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      paddingVertical: SPACING.xs + 2,
      paddingHorizontal: SPACING.sm,
      backgroundColor: colors.inputBackground,
      borderRadius: SPACING.xs + 2,
      marginBottom: SPACING.xs + 2,
    },
    reportEntryDate: {
      fontSize: TYPOGRAPHY.body.fontSize,
      color: colors.text,
    },
    reportEntryDuration: {
      fontSize: TYPOGRAPHY.body.fontSize,
      fontWeight: TYPOGRAPHY.heading.fontWeight,
      color: colors.primary,
    },
    userBreakdownRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingVertical: SPACING.md,
      paddingHorizontal: SPACING.md,
      backgroundColor: colors.inputBackground,
      borderRadius: SPACING.sm,
      marginBottom: SPACING.sm,
    },
    userBreakdownInfo: {
      flex: 1,
    },
    userBreakdownName: {
      fontSize: 15,
      fontWeight: TYPOGRAPHY.heading.fontWeight,
      color: colors.text,
    },
    userBreakdownEntries: {
      fontSize: TYPOGRAPHY.caption.fontSize,
      color: colors.textSecondary,
      marginTop: 2,
    },
    userBreakdownHours: {
      fontSize: TYPOGRAPHY.headingMedium.fontSize,
      fontWeight: '700',
      color: colors.primary,
    },

    emptyState: {
      alignItems: 'center',
      justifyContent: 'center',
      padding: SPACING.xxl + SPACING.sm,
    },
    emptyStateText: {
      fontSize: TYPOGRAPHY.headingMedium.fontSize,
      color: colors.textSecondary,
      marginTop: SPACING.md,
      textAlign: 'center',
    },

    timeEditContainer: {
      marginTop: SPACING.md,
      padding: SPACING.lg,
      backgroundColor: colors.inputBackground,
      borderRadius: CARD.borderRadius,
    },
    timeEditRow: {
      marginBottom: SPACING.lg,
    },
    timeEditLabel: {
      fontSize: TYPOGRAPHY.body.fontSize,
      fontWeight: TYPOGRAPHY.heading.fontWeight,
      color: colors.text,
      marginBottom: SPACING.sm,
    },
    timeInputRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: SPACING.sm,
    },
    timeInput: {
      backgroundColor: colors.surface,
      borderRadius: SPACING.sm,
      paddingVertical: SPACING.md,
      paddingHorizontal: SPACING.md + 2,
      fontSize: TYPOGRAPHY.heading.fontSize,
      fontWeight: TYPOGRAPHY.heading.fontWeight,
      color: colors.text,
      textAlign: 'center',
      minWidth: 50,
      borderWidth: CARD.borderWidth,
      borderColor: colors.border,
    },
    timeColon: {
      fontSize: TYPOGRAPHY.screenTitle.fontSize,
      fontWeight: '700',
      color: colors.text,
    },
    periodToggle: {
      flexDirection: 'row',
      backgroundColor: colors.surface,
      borderRadius: SPACING.sm,
      borderWidth: CARD.borderWidth,
      borderColor: colors.border,
      overflow: 'hidden',
    },
    periodButton: {
      paddingVertical: SPACING.md,
      paddingHorizontal: SPACING.md + 2,
    },
    periodButtonActive: {
      backgroundColor: colors.primary,
    },
    periodButtonText: {
      fontSize: TYPOGRAPHY.body.fontSize,
      fontWeight: TYPOGRAPHY.heading.fontWeight,
      color: colors.textSecondary,
    },
    periodButtonTextActive: {
      color: '#fff',
    },
    timeEditActions: {
      flexDirection: 'row',
      gap: SPACING.md,
      marginTop: SPACING.sm,
    },
    timeEditButton: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: SPACING.md,
      borderRadius: SPACING.sm,
      gap: SPACING.xs + 2,
    },
    timeEditSaveButton: {
      backgroundColor: colors.primary,
    },
    timeEditCancelButton: {
      backgroundColor: colors.textSecondary,
    },
    timeEditButtonText: {
      color: '#fff',
      fontSize: TYPOGRAPHY.body.fontSize,
      fontWeight: TYPOGRAPHY.heading.fontWeight,
    },

    statusBadgeContainer: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: SPACING.sm,
      marginTop: SPACING.xs + 2,
    },
    statusBadge: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: SPACING.md,
      paddingVertical: SPACING.xs + 2,
      borderRadius: SPACING.lg,
      gap: SPACING.xs + 2,
    },
    statusBadgeHomebase: {
      backgroundColor: '#d1fae5',
      borderWidth: 1,
      borderColor: '#10b981',
    },
    statusBadgeTraveling: {
      backgroundColor: '#fef3c7',
      borderWidth: 1,
      borderColor: '#f59e0b',
    },
    statusBadgeJobSite: {
      backgroundColor: '#dbeafe',
      borderWidth: 1,
      borderColor: '#3b82f6',
    },
    statusBadgeBreak: {
      backgroundColor: '#fce7f3',
      borderWidth: 1,
      borderColor: '#ec4899',
    },
    statusBadgeText: {
      fontSize: TYPOGRAPHY.caption.fontSize,
      fontWeight: TYPOGRAPHY.heading.fontWeight,
    },
    statusBadgeTextHomebase: {
      color: '#047857',
    },
    statusBadgeTextTraveling: {
      color: '#d97706',
    },
    statusBadgeTextJobSite: {
      color: '#2563eb',
    },
    statusBadgeTextBreak: {
      color: '#db2777',
    },

    reportSmallTag: {
      fontSize: 11,
      color: colors.textSecondary,
      backgroundColor: isDark ? 'rgba(255,255,255,0.08)' : 'rgba(0,0,0,0.05)',
      paddingHorizontal: SPACING.xs + 2,
      paddingVertical: 2,
      borderRadius: SPACING.xs,
      overflow: 'hidden' as const,
      marginLeft: SPACING.xs + 2,
    },

    bottomActionBar: {
      position: 'absolute' as const,
      bottom: 0,
      left: 0,
      right: 0,
      backgroundColor: colors.surface,
      borderTopWidth: 1,
      borderTopColor: isDark ? 'rgba(255,255,255,0.08)' : 'rgba(0,0,0,0.08)',
      paddingHorizontal: SPACING.xl,
      paddingTop: SPACING.md,
      paddingBottom: Platform.OS === 'ios' ? 28 : SPACING.lg,
    },
    bottomActionInner: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: SPACING.md,
    },
    clockInButton: {
      flex: 1,
      borderRadius: 14,
      overflow: 'hidden' as const,
      ...getButtonShadow(isDark),
    },
    clockOutButton: {
      flex: 1,
      borderRadius: 14,
      overflow: 'hidden' as const,
      ...getButtonShadow(isDark),
    },
    clockButtonLabel: {
      color: '#ffffff',
      fontSize: 18,
      fontWeight: '700',
      letterSpacing: 0.3,
    },
    breakActionButton: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: '#e0f2fe',
      borderWidth: 1.5,
      borderColor: '#38bdf8',
      paddingVertical: 18,
      paddingHorizontal: SPACING.lg,
      borderRadius: 14,
      gap: SPACING.xs + 2,
    },
    breakActionButtonText: {
      color: '#0284c7',
      fontSize: TYPOGRAPHY.body.fontSize,
      fontWeight: '700',
    },
    breakTimerRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: SPACING.sm,
      marginBottom: SPACING.sm,
    },
    breakTimerText: {
      fontSize: TYPOGRAPHY.body.fontSize,
      fontWeight: TYPOGRAPHY.heading.fontWeight,
      color: colors.textSecondary,
    },
    timerText: {
      fontSize: 32,
      fontWeight: '700',
      color: colors.primary,
      marginTop: SPACING.sm,
    },
    locationStatusText: {
      fontSize: 15,
      fontWeight: TYPOGRAPHY.heading.fontWeight,
      color: colors.text,
      flex: 1,
    },
    quickPhotoButton: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: SPACING.sm,
      backgroundColor: COLORS.brand,
      paddingVertical: SPACING.md,
      paddingHorizontal: SPACING.xl,
      borderRadius: SPACING.sm,
    },
    quickPhotoText: {
      color: '#fff',
      fontSize: 15,
      fontWeight: TYPOGRAPHY.heading.fontWeight,
    },
    content: {
      flex: 1,
      padding: SPACING.lg,
    },
    currentStatusCard: {
      backgroundColor: colors.primary,
      borderRadius: CARD.borderRadius,
      padding: CARD.padding,
      marginTop: SPACING.md,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      ...getElevation(1, isDark),
    },
    currentStatusLeft: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: SPACING.md,
      flex: 1,
    },
    currentStatusText: {
      fontSize: TYPOGRAPHY.headingMedium.fontSize,
      fontWeight: TYPOGRAPHY.heading.fontWeight,
      color: '#ffffff',
    },
    currentStatusSubtext: {
      fontSize: TYPOGRAPHY.label.fontSize,
      color: '#ffffff',
      opacity: 0.9,
      marginTop: 2,
    },
    jobSiteRow: {
      flexDirection: 'row' as const,
      alignItems: 'center' as const,
      justifyContent: 'center' as const,
      gap: SPACING.md,
      marginTop: SPACING.md,
    },
    jobSiteText: {
      fontSize: TYPOGRAPHY.body.fontSize,
      fontWeight: TYPOGRAPHY.heading.fontWeight as const,
      color: colors.text,
    },
    breakButton: {
      backgroundColor: colors.primary,
      paddingHorizontal: SPACING.lg,
      paddingVertical: SPACING.sm,
      borderRadius: SPACING.sm,
    },
    breakButtonText: {
      color: '#ffffff',
      fontSize: TYPOGRAPHY.body.fontSize,
      fontWeight: TYPOGRAPHY.heading.fontWeight as const,
    },
    clockSection: {
      padding: SPACING.xl,
      backgroundColor: colors.surface,
      margin: SPACING.xl,
      borderRadius: CARD.borderRadius,
      alignItems: 'center',
      ...getElevation(1, isDark),
    },
    clockButton: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: '#2D8B57',
      paddingVertical: SPACING.lg,
      paddingHorizontal: SPACING.xxl,
      borderRadius: CARD.borderRadius,
      minWidth: 200,
      gap: SPACING.sm,
    },
    clockButtonActive: {
      backgroundColor: COLORS.brand,
    },
    clockButtonText: {
      color: '#fff',
      fontSize: TYPOGRAPHY.heading.fontSize,
      fontWeight: '700',
    },
    activeTimer: {
      marginTop: SPACING.xl,
      alignItems: 'center',
    },
    timerLabel: {
      fontSize: TYPOGRAPHY.body.fontSize,
      color: colors.textSecondary,
    },
    locationStatusContainer: {
      width: '100%',
      marginBottom: SPACING.lg,
      gap: SPACING.md,
    },
    locationStatus: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: SPACING.sm,
      paddingVertical: SPACING.md,
      paddingHorizontal: SPACING.lg,
      borderRadius: SPACING.sm,
      borderWidth: 2,
    },
    locationStatus_home: {
      backgroundColor: '#ecfdf5',
      borderColor: '#10b981',
    },
    locationStatus_job_site: {
      backgroundColor: '#eff6ff',
      borderColor: '#3b82f6',
    },
    locationStatus_traveling: {
      backgroundColor: '#fef3c7',
      borderColor: '#f59e0b',
    },
    viewDetailsButton: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.primary + '15',
      paddingVertical: SPACING.md,
      paddingHorizontal: SPACING.lg,
      borderRadius: SPACING.sm,
      marginTop: SPACING.md,
      gap: SPACING.xs + 2,
    },
    viewDetailsButtonText: {
      fontSize: TYPOGRAPHY.body.fontSize,
      fontWeight: TYPOGRAPHY.heading.fontWeight,
      color: colors.primary,
    },
    productivityReportButton: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: COLORS.brand,
      paddingVertical: SPACING.md + 2,
      paddingHorizontal: SPACING.xl,
      borderRadius: CARD.borderRadius,
      margin: SPACING.xl,
      gap: SPACING.sm,
      ...getElevation(1, isDark),
    },
    productivityReportButtonText: {
      color: '#ffffff',
      fontSize: TYPOGRAPHY.headingMedium.fontSize,
      fontWeight: '700',
    },

    analyticsContainer: {
      gap: SPACING.md,
      paddingHorizontal: SPACING.lg,
      paddingTop: SPACING.md,
      paddingBottom: SPACING.xs,
    },
    kpiRow: {
      flexDirection: 'row',
      gap: 10,
    },
    kpiCard: {
      flex: 1,
      borderRadius: 12,
      padding: 14,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.cardBackground,
      alignItems: 'center',
      ...Platform.select({
        web: { boxShadow: '0 1px 4px rgba(0,0,0,0.06)' },
        default: { shadowColor: '#000', shadowOffset: { width: 0, height: 1 }, shadowOpacity: 0.06, shadowRadius: 4 },
      }),
    },
    kpiLabel: {
      fontSize: 10,
      fontWeight: '700',
      textTransform: 'uppercase',
      letterSpacing: 0.4,
      marginBottom: 6,
      color: colors.textSecondary,
    },
    kpiValue: {
      fontSize: 20,
      fontWeight: '800',
      color: colors.primary,
    },

    weeklyChartSection: {
      borderRadius: 14,
      padding: SPACING.lg,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.cardBackground,
      ...Platform.select({
        web: { boxShadow: '0 1px 4px rgba(0,0,0,0.06)' },
        default: { shadowColor: '#000', shadowOffset: { width: 0, height: 1 }, shadowOpacity: 0.06, shadowRadius: 4 },
      }),
    },
    chartSectionHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      marginBottom: 14,
    },
    chartSectionTitle: {
      fontSize: 14,
      fontWeight: '700',
      color: colors.text,
    },

    employeeFilterContainer: {
      paddingHorizontal: SPACING.lg,
      paddingBottom: SPACING.sm,
    },
    employeeFilterScroll: {
      flexDirection: 'row',
      gap: SPACING.sm,
    },
    employeeFilterChip: {
      paddingHorizontal: SPACING.md,
      paddingVertical: SPACING.sm,
      borderRadius: 20,
      backgroundColor: colors.inputBackground,
      borderWidth: 1,
      borderColor: colors.border,
    },
    employeeFilterChipActive: {
      backgroundColor: colors.primary,
      borderColor: colors.primary,
    },
    employeeFilterChipText: {
      fontSize: TYPOGRAPHY.body.fontSize,
      fontWeight: TYPOGRAPHY.heading.fontWeight,
      color: colors.textSecondary,
    },
    employeeFilterChipTextActive: {
      color: '#FFFFFF',
    },

    weeklyBreakdownSection: {
      borderRadius: 14,
      padding: SPACING.lg,
      marginHorizontal: SPACING.lg,
      marginBottom: SPACING.md,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.cardBackground,
      ...Platform.select({
        web: { boxShadow: '0 1px 4px rgba(0,0,0,0.06)' },
        default: { shadowColor: '#000', shadowOffset: { width: 0, height: 1 }, shadowOpacity: 0.06, shadowRadius: 4 },
      }),
    },
    weeklyBreakdownHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: SPACING.md,
    },
    weeklyBreakdownTitle: {
      fontSize: TYPOGRAPHY.headingMedium.fontSize,
      fontWeight: '700',
      color: colors.text,
    },
    weeklyBreakdownSubtitle: {
      fontSize: TYPOGRAPHY.caption.fontSize,
      color: colors.textSecondary,
      marginTop: 2,
    },
    weeklyBreakdownTotal: {
      fontSize: 18,
      fontWeight: '800',
      color: colors.primary,
    },
    employeeWeekRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingVertical: SPACING.md,
      paddingHorizontal: SPACING.md,
      backgroundColor: colors.inputBackground,
      borderRadius: SPACING.sm,
      marginBottom: SPACING.sm,
    },
    employeeWeekName: {
      fontSize: 14,
      fontWeight: '600',
      color: colors.text,
    },
    employeeWeekEntries: {
      fontSize: 11,
      color: colors.textSecondary,
      marginTop: 2,
    },
    employeeWeekHours: {
      fontSize: 16,
      fontWeight: '700',
      color: colors.primary,
    },
    employeeWeekBar: {
      height: 3,
      borderRadius: 2,
      backgroundColor: colors.primary + '30',
      marginTop: SPACING.xs,
    },
    employeeWeekBarFill: {
      height: 3,
      borderRadius: 2,
      backgroundColor: colors.primary,
    },
  });

export default getDynamicStyles;
